In [1]:
import os
import zipfile
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows',None)

In [2]:
dfs = {}

with zipfile.ZipFile("data/M3P1_Metodos_Reduccion.zip") as z:
    print("Archivos:")
    for name in z.namelist():
        
        if name.endswith("/"):
            continue

        base = os.path.basename(name)
        print(base)

        if base.endswith(".csv"):
            key = base.removesuffix(".csv")
            with z.open(name) as f:
                dfs[key] = pd.read_csv(f)

        elif base.endswith(".txt"):
            key = base.removesuffix(".txt")
            with z.open(name) as f:
                dfs[key] = pd.read_csv(f, sep="\t")

Archivos:
tam_loc.csv.csv
conjunto_de_datos_iter_00CSV20.csv

/var/folders/w3/5tjl2q2n0yn8r_8pkh98tr8m0000gn/T/ipykernel_17792/1409168344.py:16: DtypeWarning: Columns (0: ALTITUD) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[key] = pd.read_csv(f)

diccionario_datos_iter_00CSV20.csv
metadatos_iter_00_cpv2020.txt

In [3]:
for key in dfs.keys():
    print(key)
    display(dfs[key].head())

tam_loc.csv

   tam_loc               descripcion
0        1        1 a 249 habitantes
1        2     250 a 499 habitantes
2        3      500 a 999 habitantes
3        4  1 000 a 2 499 habitantes
4        5  2 500 a 4 999 habitantes

conjunto_de_datos_iter_00CSV20

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_3YMAS,P_3YMAS_F,P_3YMAS_M,P_5YMAS,P_5YMAS_F,P_5YMAS_M,P_12YMAS,P_12YMAS_F,P_12YMAS_M,P_15YMAS,P_15YMAS_F,P_15YMAS_M,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_3A5,P_3A5_F,P_3A5_M,P_6A11,P_6A11_F,P_6A11_M,P_8A14,P_8A14_F,P_8A14_M,P_12A14,P_12A14_F,P_12A14_M,P_15A17,P_15A17_F,P_15A17_M,P_18A24,P_18A24_F,P_18A24_M,P_15A49_F,P_60YMAS,P_60YMAS_F,P_60YMAS_M,REL_H_M,POB0_14,POB15_64,POB65_MAS,P_0A4,P_0A4_F,P_0A4_M,P_5A9,P_5A9_F,P_5A9_M,P_10A14,P_10A14_F,P_10A14_M,P_15A19,P_15A19_F,P_15A19_M,P_20A24,P_20A24_F,P_20A24_M,P_25A29,P_25A29_F,P_25A29_M,P_30A34,P_30A34_F,P_30A34_M,P_35A39,P_35A39_F,P_35A39_M,P_40A44,P_40A44_F,P_40A44_M,P_45A49,P_45A49_F,P_45A49_M,P_50A54,P_50A54_F,P_50A54_M,P_55A59,P_55A59_F,P_55A59_M,P_60A64,P_60A64_F,P_60A64_M,P_65A69,P_65A69_F,P_65A69_M,P_70A74,P_70A74_F,P_70A74_M,P_75A79,P_75A79_F,P_75A79_M,P_80A84,P_80A84_F,P_80A84_M,P_85YMAS,P_85YMAS_F,P_85YMAS_M,PROM_HNV,PNACENT,PNACENT_F,PNACENT_M,PNACOE,PNACOE_F,PNACOE_M,PRES2015,PRES2015_F,PRES2015_M,PRESOE15,PRESOE15_F,PRESOE15_M,P3YM_HLI,P3YM_HLI_F,P3YM_HLI_M,P3HLINHE,P3HLINHE_F,P3HLINHE_M,P3HLI_HE,P3HLI_HE_F,P3HLI_HE_M,P5_HLI,P5_HLI_NHE,P5_HLI_HE,PHOG_IND,POB_AFRO,POB_AFRO_F,POB_AFRO_M,PCON_DISC,PCDISC_MOT,PCDISC_VIS,PCDISC_LENG,PCDISC_AUD,PCDISC_MOT2,PCDISC_MEN,PCON_LIMI,PCLIM_CSB,PCLIM_VIS,PCLIM_HACO,PCLIM_OAUD,PCLIM_MOT2,PCLIM_RE_CO,PCLIM_PMEN,PSIND_LIM,P3A5_NOA,P3A5_NOA_F,P3A5_NOA_M,P6A11_NOA,P6A11_NOAF,P6A11_NOAM,P12A14NOA,P12A14NOAF,P12A14NOAM,P15A17A,P15A17A_F,P15A17A_M,P18A24A,P18A24A_F,P18A24A_M,P8A14AN,P8A14AN_F,P8A14AN_M,P15YM_AN,P15YM_AN_F,P15YM_AN_M,P15YM_SE,P15YM_SE_F,P15YM_SE_M,P15PRI_IN,P15PRI_INF,P15PRI_INM,P15PRI_CO,P15PRI_COF,P15PRI_COM,P15SEC_IN,P15SEC_INF,P15SEC_INM,P15SEC_CO,P15SEC_COF,P15SEC_COM,P18YM_PB,P18YM_PB_F,P18YM_PB_M,GRAPROES,GRAPROES_F,GRAPROES_M,PEA,PEA_F,PEA_M,PE_INAC,PE_INAC_F,PE_INAC_M,POCUPADA,POCUPADA_F,POCUPADA_M,PDESOCUP,PDESOCUP_F,PDESOCUP_M,PSINDER,PDER_SS,PDER_IMSS,PDER_ISTE,PDER_ISTEE,PAFIL_PDOM,PDER_SEGP,PDER_IMSSB,PAFIL_IPRIV,PAFIL_OTRAI,P12YM_SOLT,P12YM_CASA,P12YM_SEPA,PCATOLICA,PRO_CRIEVA,POTRAS_REL,PSIN_RELIG,TOTHOG,HOGJEF_F,HOGJEF_M,POBHOG,PHOGJEF_F,PHOGJEF_M,VIVTOT,TVIVHAB,TVIVPAR,VIVPAR_HAB,VIVPARH_CV,TVIVPARHAB,VIVPAR_DES,VIVPAR_UT,OCUPVIVPAR,PROM_OCUP,PRO_OCUP_C,VPH_PISODT,VPH_PISOTI,VPH_1DOR,VPH_2YMASD,VPH_1CUART,VPH_2CUART,VPH_3YMASC,VPH_C_ELEC,VPH_S_ELEC,VPH_AGUADV,VPH_AEASP,VPH_AGUAFV,VPH_TINACO,VPH_CISTER,VPH_EXCSA,VPH_LETR,VPH_DRENAJ,VPH_NODREN,VPH_C_SERV,VPH_NDEAED,VPH_DSADMA,VPH_NDACMM,VPH_SNBIEN,VPH_REFRI,VPH_LAVAD,VPH_HMICRO,VPH_AUTOM,VPH_MOTO,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC,TAMLOC
0,0,Total nacional,0,Total nacional,0,Total nacional,NaN,NaN,NaN,126014024,64540634,61473390,5764054,2848875,2915179,119976584,61554567,58422017,115693273,59433559,56259714,100528155,51962264,48565891,93985354,48732991,45252363,87492680,45530857,41961823,6462212,3193548,3268664,12986217,6398755,6587462,15287375,7531118,7756257,6542801,3229273,3313528,6492674,3202134,3290540,14736111,7398617,7337494,33885546,15142976,8139094,7003882,95.25,31755284,83663440,10321914,10047365,4969883,5077482,10764379,5311288,5453091,10943540,5389280,5554260,10806690,5344540,5462150,10422095,5256211,5165884,9993001,5131597,4861404,9420827,4893101,4527726,9020276,4688746,4331530,8503586,4441282,4062304,7942413,4130069,3812344,7037532,3705369,3332163,5695958,3002982,2692976,4821062,2563200,2257862,3645077,1938227,1706850,2647340,1413848,1233492,1814582,966684,847898,1175364,651552,523812,1039551,605583,433968,2.09,102724322,52519974,50204348,21611963,11222300,10389663,111075594,57288776,53786818,3807844,1889986,1917858,7364645,3783447,3581198,865972,547528,318444,6423548,3198595,3224953,7177185,785361,6317027,11800247,2576213,1297617,1278596,6179890,2939986,2691338,945162,1350802,1168098,1149257,13934448,4365234,8974853,864662,2900108,673540,2698640,1590583,104815785,2359716,1155636,1204080,577029,275189,301840,618233,283195,335038,4726359,2390407,2335952,4894125,2482980,2411145,412725,178152,234573,4456431,2677192,1779239,4841952,2791237,2050715,7731820,4042527,3689293,12325433,6515268,5810165,2913915,1297269,1616646,22833912,11857736,10976176,39977750,20408275,19569475,9.74,9.64,9.84,62281634,25465693,36815941,37891261,26379060,11512201,61121324,25137019,35984305,1160310,328674,831636,32999713,92582812,47245909,7165164,1041534,1192255,32842765,958787,2615213,1149542,34370381,54036478,12049313,97864218,14095307,248169,13314516,35219141,11474983,23744158,125514839,37418569,88096270,43903443,35233462,42300700,33630719,35156897,35219141,6155682,2514299,125514839,3.56,0.96,33833470,1235550,11186214,23887498,2085925,5460133,27527131,34805976,268863,33858339,29541708,1215497,22629812,9652823,33081729,1396774,33564054,1498766,32671764,79584,32979844,16874580,581095,30811260,25610544,16651199,16340788,4227460,7469168,23772973,32031555,13204680,13184550,30775898,18307193,15211306,6616141,4047100,1788552,3170894,15108204,852871,*
1,0,Total nacional,0,Total nacional,9998,Localidades de una vivienda,NaN,NaN,NaN,250354,96869,153485,10493,5193,5300,239441,91463,147978,232086,87931,144155,207748,76111,131637,197411,71344,126067,186968,66514,120454,10900,5270,5630,20793,10082,10711,24342,11538,12804,10337,4767,5570,10443,4830,5613,27841,11140,16701,47693,37383,13442,23941,158.45,52523,171209,26202,17848,8725,9123,17380,8526,8854,17295,8061,9234,18303,8138,10165,19981,7832,12149,20584,7125,13459,19601,6309,13292,18645,6289,12356,17934,6060,11874,16840,5940,10900,15070,5481,9589,13070,4728,8342,11181,4050,7131,9160,3343,5817,6903,2421,4482,4765,1639,3126,3017,1081,1936,2357,908,1449,*,177757,75977,101780,54046,18910,35136,184423,79893,104530,16172,6089,10083,26486,10908,15578,2712,1652,1060,22906,9203,13703,25743,2412,22464,27252,4122,1614,2508,12126,5875,5008,1940,2895,2123,2179,28067,10653,17059,2092,6916,1625,5763,2823,207052,5620,2689,2931,2920,1403,1517,2699,1190,1509,4952,2386,2566,4157,1610,2547,2393,1080,1313,24331,10532,13799,28014,11278,16736,38545,13056,25489,38809,14762,24047,14833,3143,11690,40180,15578,24602,33907,11972,21935,6.5,6.51,6.5,128289,33067,95222,68766,42827,25939,127469,32906,94563,820,161,659,86676,153663,53559,3795,552,649,84849,2883,3288,6284,63913,124916,18433,187464,29725,1117,29624,62516,8292,54224,198544,28805,169739,101390,62767,99591,60968,62091,62516,18117,20506,198544,3.18,1.03,53169,8797,30115,31851,7333,16206,38424,48426,13538,45470,8198,16498,34143,13743,44688,9825,47253,14708,35091,4842,43668,24373,5136,38199,26412,13608,30940,15001,13600,36738,40001,5797,3523,47005,8385,18981,1732,1113,12775,14143,51293,7154,*
2,0,Total nacional,0,Total nacional,9999,Localidades de dos viviendas,NaN,NaN,NaN,147125,61324,85801,6798,3407,3391,139757,57628,82129,135028,55256,79772,119223,47543,71680,111530,44275,67255,104612,41184,63428,7028,3511,3517,13506,6574,6932,16724,7679,9045,7693,3268,4425,6918,3091,3827,16336,6760,9576,29297,21277,8916,12361,139.91,35025,96250,15280,11527,5779,5748,11274,5558,5716,12224,5423,6801,11484,5140,6344,11770,4711,7059,12238,4427,7811,11315,4074,7241,10357,3825,6532,9705,3743,5962,8668,3377,5291,7878,3239,4639,6838,2823,4015,5997,2511,3486,5052,2130,2922,3852,1575,2277,2920,1182,1738,1868,793,1075,1588,725,863,*,117805,52686,65119,20274,7205,13069,114178,52604,61574,6214,1664,4550,18640,8181,10459,3098,1901,1197,14758,6205,8553,17992,2742,14467,21531,2816,1056,1760,8058,4079,3590,1664,2295,1808,1825,16685,6309,10523,1279,3982,1085,3479,1579,120888,3783,1873,1910,1782,874,908,1674,766,908,3557,1509,2048,2738,1053,1685,1527,712,815,15092,7074,8018,17660,7476,10184,21620,8064,13556,22033,9009,13024,5040,1561,3479,24056,9485,14571,19102,7672,11430,6.45,6.48,6.43,68904,18475,50429,46162,28959,17203,68215,18365,49850,689,110,579,56232,90057,23569,2312,350,485,59445,1956,1300,1504,38355,68874,10660,112351,16630,675,16432,36568,6620,29948,125099,21860,103239,61435,36676,60317,35558,36359,36568,12225,12534,125099,3.42,1.03,29302,6891,17038,19157,4351,9491,22351,28586,7607,26499,5054,9696,18089,7029,24348,6050,26036,10155,19807,2935,23841,16122,4115,21775,15880,7902,16699,8076,6330,20009,23198,3588,2177,25581,5027,11306,971,708,8247,10065,29741,5283,*
3,1,Aguascalientes,0,Total de la entidad Aguascalientes,0,Total de la Entidad,NaN,NaN,NaN,1425607,728924,696683,71864,35604,36260,1352235,692561,659674,1299669,666713,632956,1116719,576593,540126,1038904,538387,500517,960764,500089,460675,78833,38679,40154,156683,77289,79394,181905,89383,92522,77815,38206,39609,78140,38298,39842,180847,90632,90215,388917,145376,78703,66673,95.58,385195,941834,97070,124430,61452,62978,131048,64689,66359,129717,63637,66080,131967,65064,66903,127020,63866,63154,118426,60285,58141,106825,55174,51651,99257,51483,47774,92378,48539,43839,84669,44506,40163,74121,39510,34611,58865,31257,27608,48306,25871,22435,35823,19125,16698,25586,13804,11782,16581,8842,7739,10186,5789,4397,8894,5272,3622,2.11,1133247,576781,556466,276430,144420,132010,1232234,635320,596914,56422,27956,28466,2539,1043,1496,25,13,12,2461,1012,1449,2508,22,2437,5552,22425,11211,11214,71294,34507,29888,9297,12989,12726,12967,165482,49636,103289,8940,30298,6368,34556,20169,1177938,31495,15371,16124,4941,2292,2649,6812,2901,3911,55493,28286,27207,59978,31114,28864,3178,1318,1860,21908,11762,10146,25567,13286,12281,65609,33542,32067,122405,64730,57675,30347,12806,17541,288036,151759,136277,467249,240419,226830,10.35,10.32,10.38,706930,293533,413397,407903,282320,125583,692983,289268,403715,13947,4265,9682,262088,1161139,780525,92771,3786,3196,271996,1680,31789,3179,402370,593273,120740,1272419,73359,1900,74439,386445,119453,266992,1421200,395735,1025465,463972,386671,453099,375798,386011,386445,60327,16974,1421200,3.68,0.89,382634,2899,86423,299141,6390,30686,348487,384361,1210,383430,355192,2137,295903,152521,382597,1011,383148,2379,380982,184,382121,130744,876,365189,335710,238571,240381,45642,105752,312002,370411,177149,147818,359895,236003,174089,98724,70126,6021,15323,128996,1711,*
4,1,Aguascalientes,0,Total de la entidad Aguascalientes,9998,Localidades de una vivienda,NaN,NaN,NaN,3697,1510,2187,165,81,84,3532,1429,2103,3420,1377,2043,3018,1179,1839,2836,1086,1750,2609,987,1622,169,80,89,345,170,175,427,211,216,182,93,89,227,99,128,438,180,258,750,448,190,258,144.83,861,2524,312,277,133,144,281,142,139,303,149,154,348,148,200,317,131,186,300,109,191,280,89,191,272,85,187,259,103,156,238,85,153,177,72,105,197,74,123,136,54,82,106,44,62,78,35,43,58,26,32,38,19,19,32,12,20,*,2908,1216,1692,749,275,474,2721,1298,1423,152,69,83,20,3,17,0,0,0,15,3,12,20,0,15,5,52,20,32,212,110,69,18,39,38,27,418,161,226,30,75,24,95,56,3044,84,36,48,25,17,8,34,16,18,133,53,80,93,33,60,19,10,9,180,78,102,209,79,130,378,152,226,470,207,263,157,37,120,832,291,541,722,289,433,8.14,8.2,8.11,2077,506,1571,939,673,266,2060,497,1563,17,9,8,1067,2472,1090,113,4,0,1242,2,31,13,1037,1695,285,3250,223,11,195,807,123,684,3137,532,2605,1368,813,1354,799,801,807,233,322,3137,3.89,1.02,771,30,270,531,39,116,646,723,78,694,195,107,608,405,708,27,719,82,610,16,704,203,12,632,561,276,529,216,407,650,684,167,43,732,205,212,48,41,39,62,530,20,*

diccionario_datos_iter_00CSV20

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,CENSO DE POBLACIÓN Y VIVIENDA 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Relación de indicadores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Cuarta edición,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Núm.,Indicador,Descripción,Mnemónico,Rangos,Longitud,NaN,NaN,NaN,NaN
4,1,Clave de entidad federativa,Código que identifica a la entidad federativa....,ENTIDAD,00…32,2,NaN,NaN,NaN,NaN

metadatos_iter_00_cpv2020

              identifier: MEX-INEGI.ESD2.01-CPV-2020
0  title: Principales resultados por localidad (I...
1                                      description:
2  INEGI. Censo de Población y Vivienda 2020. SNI...
3  Conjunto de indicadores de población y viviend...
4                                              NOTA:

In [4]:
censo = dfs["conjunto_de_datos_iter_00CSV20"].copy()
print(f'Registros totales (todos los niveles): {censo.shape[0]:,}')
censo.head()

Registros totales (todos los niveles): 195,662

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_3YMAS,P_3YMAS_F,P_3YMAS_M,P_5YMAS,P_5YMAS_F,P_5YMAS_M,P_12YMAS,P_12YMAS_F,P_12YMAS_M,P_15YMAS,P_15YMAS_F,P_15YMAS_M,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_3A5,P_3A5_F,P_3A5_M,P_6A11,P_6A11_F,P_6A11_M,P_8A14,P_8A14_F,P_8A14_M,P_12A14,P_12A14_F,P_12A14_M,P_15A17,P_15A17_F,P_15A17_M,P_18A24,P_18A24_F,P_18A24_M,P_15A49_F,P_60YMAS,P_60YMAS_F,P_60YMAS_M,REL_H_M,POB0_14,POB15_64,POB65_MAS,P_0A4,P_0A4_F,P_0A4_M,P_5A9,P_5A9_F,P_5A9_M,P_10A14,P_10A14_F,P_10A14_M,P_15A19,P_15A19_F,P_15A19_M,P_20A24,P_20A24_F,P_20A24_M,P_25A29,P_25A29_F,P_25A29_M,P_30A34,P_30A34_F,P_30A34_M,P_35A39,P_35A39_F,P_35A39_M,P_40A44,P_40A44_F,P_40A44_M,P_45A49,P_45A49_F,P_45A49_M,P_50A54,P_50A54_F,P_50A54_M,P_55A59,P_55A59_F,P_55A59_M,P_60A64,P_60A64_F,P_60A64_M,P_65A69,P_65A69_F,P_65A69_M,P_70A74,P_70A74_F,P_70A74_M,P_75A79,P_75A79_F,P_75A79_M,P_80A84,P_80A84_F,P_80A84_M,P_85YMAS,P_85YMAS_F,P_85YMAS_M,PROM_HNV,PNACENT,PNACENT_F,PNACENT_M,PNACOE,PNACOE_F,PNACOE_M,PRES2015,PRES2015_F,PRES2015_M,PRESOE15,PRESOE15_F,PRESOE15_M,P3YM_HLI,P3YM_HLI_F,P3YM_HLI_M,P3HLINHE,P3HLINHE_F,P3HLINHE_M,P3HLI_HE,P3HLI_HE_F,P3HLI_HE_M,P5_HLI,P5_HLI_NHE,P5_HLI_HE,PHOG_IND,POB_AFRO,POB_AFRO_F,POB_AFRO_M,PCON_DISC,PCDISC_MOT,PCDISC_VIS,PCDISC_LENG,PCDISC_AUD,PCDISC_MOT2,PCDISC_MEN,PCON_LIMI,PCLIM_CSB,PCLIM_VIS,PCLIM_HACO,PCLIM_OAUD,PCLIM_MOT2,PCLIM_RE_CO,PCLIM_PMEN,PSIND_LIM,P3A5_NOA,P3A5_NOA_F,P3A5_NOA_M,P6A11_NOA,P6A11_NOAF,P6A11_NOAM,P12A14NOA,P12A14NOAF,P12A14NOAM,P15A17A,P15A17A_F,P15A17A_M,P18A24A,P18A24A_F,P18A24A_M,P8A14AN,P8A14AN_F,P8A14AN_M,P15YM_AN,P15YM_AN_F,P15YM_AN_M,P15YM_SE,P15YM_SE_F,P15YM_SE_M,P15PRI_IN,P15PRI_INF,P15PRI_INM,P15PRI_CO,P15PRI_COF,P15PRI_COM,P15SEC_IN,P15SEC_INF,P15SEC_INM,P15SEC_CO,P15SEC_COF,P15SEC_COM,P18YM_PB,P18YM_PB_F,P18YM_PB_M,GRAPROES,GRAPROES_F,GRAPROES_M,PEA,PEA_F,PEA_M,PE_INAC,PE_INAC_F,PE_INAC_M,POCUPADA,POCUPADA_F,POCUPADA_M,PDESOCUP,PDESOCUP_F,PDESOCUP_M,PSINDER,PDER_SS,PDER_IMSS,PDER_ISTE,PDER_ISTEE,PAFIL_PDOM,PDER_SEGP,PDER_IMSSB,PAFIL_IPRIV,PAFIL_OTRAI,P12YM_SOLT,P12YM_CASA,P12YM_SEPA,PCATOLICA,PRO_CRIEVA,POTRAS_REL,PSIN_RELIG,TOTHOG,HOGJEF_F,HOGJEF_M,POBHOG,PHOGJEF_F,PHOGJEF_M,VIVTOT,TVIVHAB,TVIVPAR,VIVPAR_HAB,VIVPARH_CV,TVIVPARHAB,VIVPAR_DES,VIVPAR_UT,OCUPVIVPAR,PROM_OCUP,PRO_OCUP_C,VPH_PISODT,VPH_PISOTI,VPH_1DOR,VPH_2YMASD,VPH_1CUART,VPH_2CUART,VPH_3YMASC,VPH_C_ELEC,VPH_S_ELEC,VPH_AGUADV,VPH_AEASP,VPH_AGUAFV,VPH_TINACO,VPH_CISTER,VPH_EXCSA,VPH_LETR,VPH_DRENAJ,VPH_NODREN,VPH_C_SERV,VPH_NDEAED,VPH_DSADMA,VPH_NDACMM,VPH_SNBIEN,VPH_REFRI,VPH_LAVAD,VPH_HMICRO,VPH_AUTOM,VPH_MOTO,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC,TAMLOC
0,0,Total nacional,0,Total nacional,0,Total nacional,NaN,NaN,NaN,126014024,64540634,61473390,5764054,2848875,2915179,119976584,61554567,58422017,115693273,59433559,56259714,100528155,51962264,48565891,93985354,48732991,45252363,87492680,45530857,41961823,6462212,3193548,3268664,12986217,6398755,6587462,15287375,7531118,7756257,6542801,3229273,3313528,6492674,3202134,3290540,14736111,7398617,7337494,33885546,15142976,8139094,7003882,95.25,31755284,83663440,10321914,10047365,4969883,5077482,10764379,5311288,5453091,10943540,5389280,5554260,10806690,5344540,5462150,10422095,5256211,5165884,9993001,5131597,4861404,9420827,4893101,4527726,9020276,4688746,4331530,8503586,4441282,4062304,7942413,4130069,3812344,7037532,3705369,3332163,5695958,3002982,2692976,4821062,2563200,2257862,3645077,1938227,1706850,2647340,1413848,1233492,1814582,966684,847898,1175364,651552,523812,1039551,605583,433968,2.09,102724322,52519974,50204348,21611963,11222300,10389663,111075594,57288776,53786818,3807844,1889986,1917858,7364645,3783447,3581198,865972,547528,318444,6423548,3198595,3224953,7177185,785361,6317027,11800247,2576213,1297617,1278596,6179890,2939986,2691338,945162,1350802,1168098,1149257,13934448,4365234,8974853,864662,2900108,673540,2698640,1590583,104815785,2359716,1155636,1204080,577029,275189,301840,618233,283195,335038,4726359,2390407,2335952,4894125,2482980,2411145,412725,178152,234573,4456431,2677192,1779239,4841952,2791237,2050715,7731820,4042527,3689293,12325433,6515268,5810165,2913915,1297269,1616646,22833912,11857736,10976176,39977750,20408275,19569475,9.74,9.64,9.84,62281634,25465693,36815941,37891261,26379060,11512201,61121324,25137019,35984305,1160310,328674,831636,32999713,92582812,47245909,7165164,1041534,1192255,32842765,958787,2615213,1149542,34370381,54036478,12049313,97864218,14095307,248169,13314516,35219141,11474983,23744158,125514839,37418569,88096270,43903443,35233462,42300700,33630719,35156897,35219141,6155682,2514299,125514839,3.56,0.96,33833470,1235550,11186214,23887498,2085925,5460133,27527131,34805976,268863,33858339,29541708,1215497,22629812,9652823,33081729,1396774,33564054,1498766,32671764,79584,32979844,16874580,581095,30811260,25610544,16651199,16340788,4227460,7469168,23772973,32031555,13204680,13184550,30775898,18307193,15211306,6616141,4047100,1788552,3170894,15108204,852871,*
1,0,Total nacional,0,Total nacional,9998,Localidades de una vivienda,NaN,NaN,NaN,250354,96869,153485,10493,5193,5300,239441,91463,147978,232086,87931,144155,207748,76111,131637,197411,71344,126067,186968,66514,120454,10900,5270,5630,20793,10082,10711,24342,11538,12804,10337,4767,5570,10443,4830,5613,27841,11140,16701,47693,37383,13442,23941,158.45,52523,171209,26202,17848,8725,9123,17380,8526,8854,17295,8061,9234,18303,8138,10165,19981,7832,12149,20584,7125,13459,19601,6309,13292,18645,6289,12356,17934,6060,11874,16840,5940,10900,15070,5481,9589,13070,4728,8342,11181,4050,7131,9160,3343,5817,6903,2421,4482,4765,1639,3126,3017,1081,1936,2357,908,1449,*,177757,75977,101780,54046,18910,35136,184423,79893,104530,16172,6089,10083,26486,10908,15578,2712,1652,1060,22906,9203,13703,25743,2412,22464,27252,4122,1614,2508,12126,5875,5008,1940,2895,2123,2179,28067,10653,17059,2092,6916,1625,5763,2823,207052,5620,2689,2931,2920,1403,1517,2699,1190,1509,4952,2386,2566,4157,1610,2547,2393,1080,1313,24331,10532,13799,28014,11278,16736,38545,13056,25489,38809,14762,24047,14833,3143,11690,40180,15578,24602,33907,11972,21935,6.5,6.51,6.5,128289,33067,95222,68766,42827,25939,127469,32906,94563,820,161,659,86676,153663,53559,3795,552,649,84849,2883,3288,6284,63913,124916,18433,187464,29725,1117,29624,62516,8292,54224,198544,28805,169739,101390,62767,99591,60968,62091,62516,18117,20506,198544,3.18,1.03,53169,8797,30115,31851,7333,16206,38424,48426,13538,45470,8198,16498,34143,13743,44688,9825,47253,14708,35091,4842,43668,24373,5136,38199,26412,13608,30940,15001,13600,36738,40001,5797,3523,47005,8385,18981,1732,1113,12775,14143,51293,7154,*
2,0,Total nacional,0,Total nacional,9999,Localidades de dos viviendas,NaN,NaN,NaN,147125,61324,85801,6798,3407,3391,139757,57628,82129,135028,55256,79772,119223,47543,71680,111530,44275,67255,104612,41184,63428,7028,3511,3517,13506,6574,6932,16724,7679,9045,7693,3268,4425,6918,3091,3827,16336,6760,9576,29297,21277,8916,12361,139.91,35025,96250,15280,11527,5779,5748,11274,5558,5716,12224,5423,6801,11484,5140,6344,11770,4711,7059,12238,4427,7811,11315,4074,7241,10357,3825,6532,9705,3743,5962,8668,3377,5291,7878,3239,4639,6838,2823,4015,5997,2511,3486,5052,2130,2922,3852,1575,2277,2920,1182,1738,1868,793,1075,1588,725,863,*,117805,52686,65119,20274,7205,13069,114178,52604,61574,6214,1664,4550,18640,8181,10459,3098,1901,1197,14758,6205,8553,17992,2742,14467,21531,2816,1056,1760,8058,4079,3590,1664,2295,1808,1825,16685,6309,10523,1279,3982,1085,3479,1579,120888,3783,1873,1910,1782,874,908,1674,766,908,3557,1509,2048,2738,1053,1685,1527,712,815,15092,7074,8018,17660,7476,10184,21620,8064,13556,22033,9009,13024,5040,1561,3479,24056,9485,14571,19102,7672,11430,6.45,6.48,6.43,68904,18475,50429,46162,28959,17203,68215,18365,49850,689,110,579,56232,90057,23569,2312,350,485,59445,1956,1300,1504,38355,68874,10660,112351,16630,675,16432,36568,6620,29948,125099,21860,103239,61435,36676,60317,35558,36359,36568,12225,12534,125099,3.42,1.03,29302,6891,17038,19157,4351,9491,22351,28586,7607,26499,5054,9696,18089,7029,24348,6050,26036,10155,19807,2935,23841,16122,4115,21775,15880,7902,16699,8076,6330,20009,23198,3588,2177,25581,5027,11306,971,708,8247,10065,29741,5283,*
3,1,Aguascalientes,0,Total de la entidad Aguascalientes,0,Total de la Entidad,NaN,NaN,NaN,1425607,728924,696683,71864,35604,36260,1352235,692561,659674,1299669,666713,632956,1116719,576593,540126,1038904,538387,500517,960764,500089,460675,78833,38679,40154,156683,77289,79394,181905,89383,92522,77815,38206,39609,78140,38298,39842,180847,90632,90215,388917,145376,78703,66673,95.58,385195,941834,97070,124430,61452,62978,131048,64689,66359,129717,63637,66080,131967,65064,66903,127020,63866,63154,118426,60285,58141,106825,55174,51651,99257,51483,47774,92378,48539,43839,84669,44506,40163,74121,39510,34611,58865,31257,27608,48306,25871,22435,35823,19125,16698,25586,13804,11782,16581,8842,7739,10186,5789,4397,8894,5272,3622,2.11,1133247,576781,556466,276430,144420,132010,1232234,635320,596914,56422,27956,28466,2539,1043,1496,25,13,12,2461,1012,1449,2508,22,2437,5552,22425,11211,11214,71294,34507,29888,9297,12989,12726,12967,165482,49636,103289,8940,30298,6368,34556,20169,1177938,31495,15371,16124,4941,2292,2649,6812,2901,3911,55493,28286,27207,59978,31114,28864,3178,1318,1860,21908,11762,10146,25567,13286,12281,65609,33542,32067,122405,64730,57675,30347,12806,17541,288036,151759,136277,467249,240419,226830,10.35,10.32,10.38,706930,293533,413397,407903,282320,125583,692983,289268,403715,13947,4265,9682,262088,1161139,780525,92771,3786,3196,271996,1680,31789,3179,402370,593273,120740,1272419,73359,1900,74439,386445,119453,266992,1421200,395735,1025465,463972,386671,453099,375798,386011,386445,60327,16974,1421200,3.68,0.89,382634,2899,86423,299141,6390,30686,348487,384361,1210,383430,355192,2137,295903,152521,382597,1011,383148,2379,380982,184,382121,130744,876,365189,335710,238571,240381,45642,105752,312002,370411,177149,147818,359895,236003,174089,98724,70126,6021,15323,128996,1711,*
4,1,Aguascalientes,0,Total de la entidad Aguascalientes,9998,Localidades de una vivienda,NaN,NaN,NaN,3697,1510,2187,165,81,84,3532,1429,2103,3420,1377,2043,3018,1179,1839,2836,1086,1750,2609,987,1622,169,80,89,345,170,175,427,211,216,182,93,89,227,99,128,438,180,258,750,448,190,258,144.83,861,2524,312,277,133,144,281,142,139,303,149,154,348,148,200,317,131,186,300,109,191,280,89,191,272,85,187,259,103,156,238,85,153,177,72,105,197,74,123,136,54,82,106,44,62,78,35,43,58,26,32,38,19,19,32,12,20,*,2908,1216,1692,749,275,474,2721,1298,1423,152,69,83,20,3,17,0,0,0,15,3,12,20,0,15,5,52,20,32,212,110,69,18,39,38,27,418,161,226,30,75,24,95,56,3044,84,36,48,25,17,8,34,16,18,133,53,80,93,33,60,19,10,9,180,78,102,209,79,130,378,152,226,470,207,263,157,37,120,832,291,541,722,289,433,8.14,8.2,8.11,2077,506,1571,939,673,266,2060,497,1563,17,9,8,1067,2472,1090,113,4,0,1242,2,31,13,1037,1695,285,3250,223,11,195,807,123,684,3137,532,2605,1368,813,1354,799,801,807,233,322,3137,3.89,1.02,771,30,270,531,39,116,646,723,78,694,195,107,608,405,708,27,719,82,610,16,704,203,12,632,561,276,529,216,407,650,684,167,43,732,205,212,48,41,39,62,530,20,*

In [6]:
municipios = censo[(censo["ENTIDAD"]>0) & (censo["MUN"]>0) & (censo["LOC"]==0)].copy()
print(f'Registros municipales: {municipios.shape[0]:,}')
print(f'Número de variables disponibles: {municipios.shape[1]}')
municipios.head()

Registros municipales: 2,469
Número de variables disponibles: 286

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_3YMAS,P_3YMAS_F,P_3YMAS_M,P_5YMAS,P_5YMAS_F,P_5YMAS_M,P_12YMAS,P_12YMAS_F,P_12YMAS_M,P_15YMAS,P_15YMAS_F,P_15YMAS_M,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_3A5,P_3A5_F,P_3A5_M,P_6A11,P_6A11_F,P_6A11_M,P_8A14,P_8A14_F,P_8A14_M,P_12A14,P_12A14_F,P_12A14_M,P_15A17,P_15A17_F,P_15A17_M,P_18A24,P_18A24_F,P_18A24_M,P_15A49_F,P_60YMAS,P_60YMAS_F,P_60YMAS_M,REL_H_M,POB0_14,POB15_64,POB65_MAS,P_0A4,P_0A4_F,P_0A4_M,P_5A9,P_5A9_F,P_5A9_M,P_10A14,P_10A14_F,P_10A14_M,P_15A19,P_15A19_F,P_15A19_M,P_20A24,P_20A24_F,P_20A24_M,P_25A29,P_25A29_F,P_25A29_M,P_30A34,P_30A34_F,P_30A34_M,P_35A39,P_35A39_F,P_35A39_M,P_40A44,P_40A44_F,P_40A44_M,P_45A49,P_45A49_F,P_45A49_M,P_50A54,P_50A54_F,P_50A54_M,P_55A59,P_55A59_F,P_55A59_M,P_60A64,P_60A64_F,P_60A64_M,P_65A69,P_65A69_F,P_65A69_M,P_70A74,P_70A74_F,P_70A74_M,P_75A79,P_75A79_F,P_75A79_M,P_80A84,P_80A84_F,P_80A84_M,P_85YMAS,P_85YMAS_F,P_85YMAS_M,PROM_HNV,PNACENT,PNACENT_F,PNACENT_M,PNACOE,PNACOE_F,PNACOE_M,PRES2015,PRES2015_F,PRES2015_M,PRESOE15,PRESOE15_F,PRESOE15_M,P3YM_HLI,P3YM_HLI_F,P3YM_HLI_M,P3HLINHE,P3HLINHE_F,P3HLINHE_M,P3HLI_HE,P3HLI_HE_F,P3HLI_HE_M,P5_HLI,P5_HLI_NHE,P5_HLI_HE,PHOG_IND,POB_AFRO,POB_AFRO_F,POB_AFRO_M,PCON_DISC,PCDISC_MOT,PCDISC_VIS,PCDISC_LENG,PCDISC_AUD,PCDISC_MOT2,PCDISC_MEN,PCON_LIMI,PCLIM_CSB,PCLIM_VIS,PCLIM_HACO,PCLIM_OAUD,PCLIM_MOT2,PCLIM_RE_CO,PCLIM_PMEN,PSIND_LIM,P3A5_NOA,P3A5_NOA_F,P3A5_NOA_M,P6A11_NOA,P6A11_NOAF,P6A11_NOAM,P12A14NOA,P12A14NOAF,P12A14NOAM,P15A17A,P15A17A_F,P15A17A_M,P18A24A,P18A24A_F,P18A24A_M,P8A14AN,P8A14AN_F,P8A14AN_M,P15YM_AN,P15YM_AN_F,P15YM_AN_M,P15YM_SE,P15YM_SE_F,P15YM_SE_M,P15PRI_IN,P15PRI_INF,P15PRI_INM,P15PRI_CO,P15PRI_COF,P15PRI_COM,P15SEC_IN,P15SEC_INF,P15SEC_INM,P15SEC_CO,P15SEC_COF,P15SEC_COM,P18YM_PB,P18YM_PB_F,P18YM_PB_M,GRAPROES,GRAPROES_F,GRAPROES_M,PEA,PEA_F,PEA_M,PE_INAC,PE_INAC_F,PE_INAC_M,POCUPADA,POCUPADA_F,POCUPADA_M,PDESOCUP,PDESOCUP_F,PDESOCUP_M,PSINDER,PDER_SS,PDER_IMSS,PDER_ISTE,PDER_ISTEE,PAFIL_PDOM,PDER_SEGP,PDER_IMSSB,PAFIL_IPRIV,PAFIL_OTRAI,P12YM_SOLT,P12YM_CASA,P12YM_SEPA,PCATOLICA,PRO_CRIEVA,POTRAS_REL,PSIN_RELIG,TOTHOG,HOGJEF_F,HOGJEF_M,POBHOG,PHOGJEF_F,PHOGJEF_M,VIVTOT,TVIVHAB,TVIVPAR,VIVPAR_HAB,VIVPARH_CV,TVIVPARHAB,VIVPAR_DES,VIVPAR_UT,OCUPVIVPAR,PROM_OCUP,PRO_OCUP_C,VPH_PISODT,VPH_PISOTI,VPH_1DOR,VPH_2YMASD,VPH_1CUART,VPH_2CUART,VPH_3YMASC,VPH_C_ELEC,VPH_S_ELEC,VPH_AGUADV,VPH_AEASP,VPH_AGUAFV,VPH_TINACO,VPH_CISTER,VPH_EXCSA,VPH_LETR,VPH_DRENAJ,VPH_NODREN,VPH_C_SERV,VPH_NDEAED,VPH_DSADMA,VPH_NDACMM,VPH_SNBIEN,VPH_REFRI,VPH_LAVAD,VPH_HMICRO,VPH_AUTOM,VPH_MOTO,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC,TAMLOC
6,1,Aguascalientes,1,Aguascalientes,0,Total del Municipio,NaN,NaN,NaN,948990,486917,462073,44372,21893,22479,903684,464556,439128,871193,448552,422641,756970,392252,364718,707473,368028,339445,657539,343551,313988,48767,23951,24816,97947,48353,49594,114551,56248,58303,49497,24224,25273,49934,24477,25457,120452,60159,60293,260277,102987,56724,46263,94.9,240583,639532,67941,76863,37897,38966,81713,40366,41347,82007,40158,41849,85161,41939,43222,85225,42697,42528,80077,40446,39631,71850,36831,35019,66892,34639,32253,62159,32704,29455,58264,31021,27243,52400,28200,24200,42458,22827,19631,35046,18957,16089,25677,13907,11770,18157,9980,8177,11458,6228,5230,6872,4055,2817,5777,3597,2180,1.98,723960,369304,354656,214908,112801,102107,821875,425161,396714,42481,21032,21449,1839,754,1085,8,4,4,1792,737,1055,1822,8,1776,4050,15170,7560,7610,47525,23117,20047,5894,8636,8226,8618,116705,34873,73664,5980,21547,4413,24523,13945,777394,18639,9130,9509,2877,1360,1517,3907,1671,2236,36490,18550,17940,44885,23031,21854,1851,772,1079,11618,6599,5019,14576,7917,6659,33308,18056,15252,76256,41402,34854,19144,8184,10960,182540,95438,87102,354455,181821,172634,10.84,10.75,10.93,486675,208788,277887,269195,182985,86210,476502,205402,271100,10173,3386,6787,173199,774363,575318,65237,2352,2563,120974,1064,25703,2346,277819,391570,87312,831010,55328,1539,58531,266778,85732,181046,945505,273935,671570,313256,266942,304033,257719,266508,266778,37113,9201,945505,3.54,0.84,264662,1530,55437,210784,3185,17449,245585,265785,438,265232,254151,989,199994,122801,265261,520,265392,798,264378,53,264988,88348,380,254959,234193,176002,169694,26624,54393,221315,257061,136923,116647,251719,178619,130290,80951,56131,3299,7293,74227,731,*
574,1,Aguascalientes,2,Asientos,0,Total del Municipio,NaN,NaN,NaN,51536,26275,25261,3170,1639,1531,48346,24626,23720,46095,23532,22563,38399,19682,18717,35250,18088,17162,32032,16536,15496,3342,1632,1710,6605,3312,3293,7612,3815,3797,3149,1594,1555,3218,1552,1666,6581,3268,3313,13564,4697,2416,2281,96.14,16266,31919,3331,5421,2733,2688,5473,2732,2741,5372,2712,2660,5282,2559,2723,4517,2261,2256,3972,2079,1893,3670,1951,1719,3288,1749,1539,3008,1606,1402,2720,1359,1361,2299,1194,1105,1797,914,883,1366,716,650,1046,539,507,859,434,425,578,293,285,427,210,217,421,224,197,2.62,45117,22833,22284,6025,3245,2780,44824,22971,21853,936,492,444,22,9,13,0,0,0,22,9,13,22,0,22,43,225,115,110,2886,1425,1206,379,514,551,505,4551,1498,2758,261,914,191,826,692,43707,1509,732,777,283,135,148,331,152,179,2148,1086,1062,1398,745,653,108,42,66,1242,601,641,1223,573,650,4515,2090,2425,5057,2558,2499,1144,476,668,13014,7001,6013,8892,4655,4237,8.54,8.68,8.38,21440,7142,14298,16864,12515,4349,21014,7069,13945,426,73,353,7590,43922,17762,1908,394,17,23997,24,93,101,13043,22095,3259,48757,1648,14,1079,12542,3191,9351,51474,11539,39935,15353,12544,15339,12530,12522,12542,2170,639,51474,4.1,1.07,12330,184,3617,8897,487,1564,10462,12420,95,12390,7637,124,10453,1834,11968,75,12067,447,11951,13,11928,4779,102,11071,10306,5351,6639,3174,5587,8897,11794,2826,1690,10682,4526,3882,596,556,377,1447,7206,177,*
749,1,Aguascalientes,3,Calvillo,0,Total del Municipio,NaN,NaN,NaN,58250,29687,28563,3159,1581,1578,55056,28088,26968,52691,26929,25762,44778,23068,21710,41495,21446,20049,38275,19860,18415,3530,1748,1782,6748,3272,3476,7820,3825,3995,3283,1622,1661,3220,1586,1634,6935,3525,3410,14665,7829,4045,3784,96.21,16720,35854,5641,5524,2740,2784,5638,2769,2869,5558,2714,2844,5363,2699,2664,4792,2412,2380,4388,2334,2054,3933,2062,1871,3453,1781,1672,3496,1817,1679,3103,1560,1543,2850,1515,1335,2288,1221,1067,2188,1173,1015,1831,916,915,1463,740,723,1025,496,529,684,367,317,638,353,285,2.67,50331,25673,24658,6566,3341,3225,50478,26070,24408,1117,547,570,76,35,41,1,1,0,74,33,41,74,1,72,173,266,112,154,4088,2079,1640,556,853,762,804,6760,2138,3962,359,1293,195,1505,1191,46834,1688,797,891,252,112,140,445,176,269,1907,1047,860,1456,838,618,164,64,100,1862,854,1008,2114,990,1124,6231,2797,3434,7694,3733,3961,1565,576,989,13314,7563,5751,9402,5132,4270,8.05,8.31,7.78,25976,9436,16540,18638,13600,5038,25597,9342,16255,379,94,285,11832,46370,10187,3139,127,332,32383,147,217,134,15846,24567,4364,55696,1141,9,1338,15546,5008,10538,58155,17221,40934,20842,15556,20748,15462,15520,15546,3437,1849,58155,3.74,0.97,15336,174,4764,10746,447,1706,13357,15398,112,15364,13788,146,14580,2133,15378,31,15407,103,15257,26,15373,6148,69,14659,13560,7992,9032,1593,2574,10716,14622,4003,4718,13666,6553,4749,1382,1352,443,904,8061,138,*
918,1,Aguascalientes,4,Cosío,0,Total del Municipio,NaN,NaN,NaN,17000,8708,8292,1032,539,493,15968,8169,7799,15254,7798,7456,12820,6622,6198,11817,6125,5692,10772,5593,5179,1062,537,525,2086,1010,1076,2374,1162,1212,1003,497,506,1045,532,513,2228,1135,1093,4552,1613,836,777,95.22,5183,10699,1118,1746,910,836,1777,857,920,1660,816,844,1719,883,836,1554,784,770,1331,660,671,1161,630,531,1065,563,502,1045,560,485,921,472,449,772,423,349,636,314,322,495,271,224,371,179,192,306,155,151,195,98,97,114,63,51,132,70,62,2.51,15495,7870,7625,1385,774,611,14878,7634,7244,297,142,155,7,1,6,0,0,0,7,1,6,7,0,7,15,2155,1103,1052,805,432,305,118,148,147,127,1933,657,1217,99,351,82,387,206,14166,423,223,200,99,51,48,77,36,41,774,405,369,541,274,267,38,17,21,371,187,184,358,174,184,1235,627,608,1419,778,641,249,134,115,4323,2262,2061,3721,1877,1844,9.08,9.1,9.07,7010,2430,4580,5774,4184,1590,6883,2401,4482,127,29,98,2347,14651,7252,1088,91,12,6439,13,33,36,4073,7532,1215,15806,769,8,409,3937,889,3048,16997,3497,13500,4845,3938,4840,3933,3931,3937,660,247,16997,4.32,1.14,3891,40,1006,2925,120,490,3321,3906,25,3900,2287,31,3068,320,3842,10,3884,47,3847,5,3843,1526,25,3518,3203,1688,2115,855,2211,2752,3671,1005,549,3424,1741,1664,223,191,139,414,1912,50,*
985,1,Aguascalientes,5,Jesús María,0,Total del Municipio,NaN,NaN,NaN,129929,65710,64219,6945,3380,3565,122845,62260,60585,117571,59690,57881,99250,50684,48566,91487,46899,44588,83807,43156,40651,7998,3903,4095,15597,7673,7924,18084,8843,9241,7763,3785,3978,7680,3743,3937,16640,8353,8287,36343,9815,5102,4713,97.73,38303,84949,6538,12219,5950,6269,13214,6538,6676,12870,6253,6617,12851,6313,6538,11469,5783,5686,10188,5197,4991,9882,5212,4670,9533,4948,4585,9049,4735,4314,8086,4155,3931,6244,3205,3039,4370,2249,2121,3277,1682,1595,2556,1351,1205,1723,897,826,1064,534,530,653,342,311,542,296,246,2.11,104356,52608,51748,23898,12288,11610,111158,56544,54614,5610,2832,2778,158,60,98,1,0,1,149,56,93,155,1,149,395,2543,1262,1281,5036,2224,2089,837,847,980,959,11904,3342,7227,801,2059,573,2466,1642,112021,3249,1588,1661,527,242,285,846,355,491,5238,2666,2572,5081,2686,2395,347,138,209,2175,1123,1052,2593,1318,1275,6532,3243,3289,12055,6173,5882,3160,1272,1888,24176,12536,11640,39383,20429,18954,10.22,10.25,10.18,65839,27412,38427,33247,23191,10056,64945,27147,37798,894,265,629,27299,102428,74274,5881,169,121,20031,144,4904,303,35667,54850,8698,118374,5208,190,5896,33214,9029,24185,129860,31646,98214,41550,33229,40588,32267,33171,33214,5989,2332,129860,3.91,0.95,32719,411,7456,25675,793,3035,29303,32977,155,32845,28396,286,24863,14354,32817,160,32867,259,32588,26,32745,9392,84,31414,29188,20743,22438,4175,12579,27281,31911,15687,12486,31408,19920,13483,9296,6582,480,1150,11447,148,*

In [ ]:
df_catalogo = dfs["diccionario_datos_iter_00CSV20"]

catalogo = (df_catalogo
            .iloc[4:, :4]
            .set_axis(df_catalogo.iloc[3, :4], axis=1)
            .dropna()
            .reset_index(drop=True))

catalogo.head()

3,Núm.,Indicador,Descripción,Mnemónico
0,1,Clave de entidad federativa,Código que identifica a la entidad federativa....,ENTIDAD
1,2,Entidad federativa,Nombre oficial de la entidad federativa.,NOM_ENT
2,3,Clave de municipio o demarcación territorial,Código que identifica al municipio o demarcaci...,MUN
3,4,Municipio o demarcación territorial,Nombre oficial del municipio o demarcación ter...,NOM_MUN
4,5,Clave de localidad,Código que identifica a la localidad al interi...,LOC

In [9]:
catalogo.to_csv("data/catalogo.csv", index= False)

In [ ]:
filtro = municipios[(municipios["NOM_ENT"]=="Ciudad de México")]
filtro

## Continuación de la práctica (Puntos 1 a 3)

A partir del documento `M3P1_Metodos_Reduccion.pdf`, en esta sección se completa:

1. EDA breve del conjunto de datos.
2. Selección y justificación de variables relevantes para marginación municipal.
3. Reducción de dimensionalidad a 2 componentes para visualización e interpretación.

In [ ]:
import zipfile
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid', palette='viridis')
pd.set_option('display.max_columns', 200)

zip_path = 'data/M3P1_Metodos_Reduccion.zip'
with zipfile.ZipFile(zip_path) as z:
    censo = pd.read_csv(
        z.open('iter_00_cpv2020/conjunto_de_datos/conjunto_de_datos_iter_00CSV20.csv'),
        low_memory=False
    )

# Convertimos columnas numéricas y preservamos nombres geográficos
for col in censo.columns:
    if col not in ['NOM_ENT', 'NOM_MUN', 'NOM_LOC', 'LONGITUD', 'LATITUD']:
        censo[col] = pd.to_numeric(censo[col], errors='coerce')

# Municipio: ENTIDAD > 0, MUN > 0, LOC == 0 (registro agregado municipal)
mun = censo[(censo['ENTIDAD'] > 0) & (censo['MUN'] > 0) & (censo['LOC'] == 0)].copy()



mun[['ENTIDAD', 'NOM_ENT', 'MUN', 'NOM_MUN', 'POBTOT', 'TVIVPARHAB']].head()

### Punto 1. EDA breve

En este análisis exploratorio se revisa:

- Tamaño de población municipal (`POBTOT`) y su asimetría.
- Condición laboral y social con variables agregadas (`PEA`, `POCUPADA`, `PSINDER`).
- Calidad de vivienda con acceso a servicios (`VPH_S_ELEC`, `VPH_NODREN`, `VPH_AGUAFV`).
- Datos faltantes en variables clave para asegurar consistencia del análisis.

In [ ]:
eda_vars = [
    'POBTOT', 'P_15YMAS', 'PEA', 'POCUPADA', 'PSINDER',
    'TVIVPARHAB', 'VPH_S_ELEC', 'VPH_NODREN', 'VPH_AGUAFV', 'VPH_SINTIC'
]

eda = mun[eda_vars].copy()

print('Resumen estadístico (variables clave):')
display(eda.describe(percentiles=[0.25, 0.5, 0.75]).T)

missing = eda.isna().mean().sort_values(ascending=False) * 100
print('\nPorcentaje de datos faltantes por variable (%):')
display(missing.to_frame('pct_missing').round(2))

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

sns.histplot(mun['POBTOT'], bins=50, kde=True, ax=axes[0], color='#2a9d8f')
axes[0].set_title('Distribución de población total municipal (POBTOT)')
axes[0].set_xlabel('Población total')

sns.boxplot(x=np.log1p(mun['POBTOT']), ax=axes[1], color='#e76f51')
axes[1].set_title('Boxplot de log(1 + POBTOT)')
axes[1].set_xlabel('log(1 + población total)')

plt.tight_layout()
plt.show()

### Hallazgos clave del Punto 1

- La distribución de `POBTOT` es altamente asimétrica: pocos municipios concentran mucha población.
- Existe heterogeneidad marcada entre municipios en condiciones de vivienda y acceso a servicios.
- El conjunto municipal es utilizable para modelado al tener bajo porcentaje de faltantes en variables principales.

### Punto 2. Variables seleccionadas para marginación y justificación

Se seleccionan indicadores en **porcentaje** para hacer comparables municipios de distinto tamaño.

Bloques conceptuales:

- **Rezago educativo**: analfabetismo y baja escolaridad.
- **Inasistencia escolar**: población infantil/adolescente fuera de la escuela.
- **Acceso a salud/seguridad social**: población sin derechohabiencia.
- **Carencias de vivienda y servicios básicos**: piso de tierra, sin drenaje, sin agua entubada, sin electricidad.
- **Brecha digital**: viviendas sin TIC.

In [ ]:
analisis_mun = mun.copy()

# Construcción de proporciones (%): evita sesgo por tamaño del municipio
analisis_mun['pct_analfabetismo_15ymas'] = 100 * analisis_mun['P15YM_AN'] / analisis_mun['P_15YMAS']
analisis_mun['pct_sin_escolaridad_15ymas'] = 100 * analisis_mun['P15YM_SE'] / analisis_mun['P_15YMAS']
analisis_mun['pct_no_asiste_6a11'] = 100 * analisis_mun['P6A11_NOA'] / analisis_mun['P_6A11']
analisis_mun['pct_no_asiste_12a14'] = 100 * analisis_mun['P12A14NOA'] / analisis_mun['P_12A14']
analisis_mun['pct_sin_derechohab'] = 100 * analisis_mun['PSINDER'] / analisis_mun['POBTOT']
analisis_mun['pct_piso_tierra'] = 100 * analisis_mun['VPH_PISOTI'] / analisis_mun['TVIVPARHAB']
analisis_mun['pct_sin_drenaje'] = 100 * analisis_mun['VPH_NODREN'] / analisis_mun['TVIVPARHAB']
analisis_mun['pct_sin_agua_entubada'] = 100 * analisis_mun['VPH_AGUAFV'] / analisis_mun['TVIVPARHAB']
analisis_mun['pct_sin_electricidad'] = 100 * analisis_mun['VPH_S_ELEC'] / analisis_mun['TVIVPARHAB']
analisis_mun['pct_sin_tic'] = 100 * analisis_mun['VPH_SINTIC'] / analisis_mun['TVIVPARHAB']

vars_marginacion = [
    'pct_analfabetismo_15ymas',
    'pct_sin_escolaridad_15ymas',
    'pct_no_asiste_6a11',
    'pct_no_asiste_12a14',
    'pct_sin_derechohab',
    'pct_piso_tierra',
    'pct_sin_drenaje',
    'pct_sin_agua_entubada',
    'pct_sin_electricidad',
    'pct_sin_tic'
]

modelo_df = analisis_mun[['ENTIDAD', 'NOM_ENT', 'MUN', 'NOM_MUN'] + vars_marginacion].replace([np.inf, -np.inf], np.nan).dropna().copy()

print(f'Municipios con información completa en variables seleccionadas: {modelo_df.shape[0]:,}')

display(modelo_df[vars_marginacion].describe().T[['mean', 'std', 'min', '50%', 'max']].round(2))

plt.figure(figsize=(10, 7))
corr = modelo_df[vars_marginacion].corr()
sns.heatmap(corr, cmap='RdBu_r', center=0, annot=False)
plt.title('Correlación entre variables seleccionadas de marginación')
plt.tight_layout()
plt.show()

top_sin_tic = modelo_df.sort_values('pct_sin_tic', ascending=False)[['NOM_ENT', 'NOM_MUN', 'pct_sin_tic']].head(10)
print('Top 10 municipios con mayor porcentaje de viviendas sin TIC:')
display(top_sin_tic.round(2))

### Hallazgos clave del Punto 2

- Las variables de rezago educativo y carencias de vivienda muestran correlaciones positivas, lo cual respalda su uso conjunto para estudiar marginación.
- `pct_sin_derechohab` y `pct_sin_drenaje` tienen promedios altos en términos relativos, señalando brechas estructurales relevantes.
- Los municipios con mayor `pct_sin_tic` se concentran en entidades con rezagos históricos, útil para focalización territorial.

### Punto 3. Reducción de dimensionalidad a 2 dimensiones

Se aplican dos enfoques de proyección:

- **PCA**: técnica lineal para capturar máxima varianza en componentes ortogonales.
- **t-SNE**: técnica no lineal para visualizar estructura local y posibles grupos.

Ambas visualizaciones apoyan la interpretación de patrones de marginación entre municipios.

In [ ]:
X = modelo_df[vars_marginacion].copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2, random_state=333)
X_pca = pca.fit_transform(X_scaled)

pca_df = modelo_df[['ENTIDAD', 'NOM_ENT', 'MUN', 'NOM_MUN']].copy()
pca_df['PC1'] = X_pca[:, 0]
pca_df['PC2'] = X_pca[:, 1]
pca_df['quintil_pc1'] = pd.qcut(pca_df['PC1'], 5, labels=['Q1', 'Q2', 'Q3', 'Q4', 'Q5'])

var_exp = pca.explained_variance_ratio_
print(f'Varianza explicada por PC1: {var_exp[0]:.4f}')
print(f'Varianza explicada por PC2: {var_exp[1]:.4f}')
print(f'Varianza explicada acumulada (2 componentes): {var_exp.sum():.4f}')

loadings = pd.DataFrame(
    pca.components_.T,
    index=vars_marginacion,
    columns=['PC1', 'PC2']
)

display(loadings.sort_values('PC1', key=np.abs, ascending=False).round(3))

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.scatterplot(
    data=pca_df,
    x='PC1',
    y='PC2',
    hue='quintil_pc1',
    palette='viridis',
    alpha=0.75,
    s=35,
    ax=axes[0]
)
axes[0].set_title('Municipios en espacio PCA (2D)')
axes[0].legend(title='Quintil PC1', bbox_to_anchor=(1.02, 1), loc='upper left')

# Biplot simplificado: direcciones de mayor contribución
axes[1].axhline(0, color='gray', lw=0.8)
axes[1].axvline(0, color='gray', lw=0.8)
for var in vars_marginacion:
    x = loadings.loc[var, 'PC1']
    y = loadings.loc[var, 'PC2']
    axes[1].arrow(0, 0, x, y, color='#264653', alpha=0.8, head_width=0.02, length_includes_head=True)
    axes[1].text(x * 1.08, y * 1.08, var, fontsize=8)

axes[1].set_xlim(-0.7, 0.7)
axes[1].set_ylim(-0.7, 0.7)
axes[1].set_title('Cargas de variables en PCA (biplot)')
axes[1].set_xlabel('PC1')
axes[1].set_ylabel('PC2')

plt.tight_layout()
plt.show()

In [ ]:
# t-SNE para visualizar estructura no lineal (solo con variables estandarizadas)
tsne = TSNE(
    n_components=2,
    random_state=42,
    init='pca',
    learning_rate='auto',
    perplexity=35
)
X_tsne = tsne.fit_transform(X_scaled)

tsne_df = modelo_df[['NOM_ENT', 'NOM_MUN']].copy()
tsne_df['TSNE1'] = X_tsne[:, 0]
tsne_df['TSNE2'] = X_tsne[:, 1]
tsne_df['quintil_pc1'] = pca_df['quintil_pc1'].values

plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=tsne_df,
    x='TSNE1',
    y='TSNE2',
    hue='quintil_pc1',
    palette='viridis',
    alpha=0.75,
    s=35
)
plt.title('Proyección t-SNE de municipios')
plt.legend(title='Quintil PC1', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

### Hallazgos clave del Punto 3

- Con 2 componentes, PCA conserva una fracción sustancial de la variabilidad total y permite ordenar municipios en un gradiente interpretable.
- Las mayores cargas en **PC1** suelen corresponder a rezago educativo y carencias de vivienda, por lo que PC1 funciona como eje sintético de marginación estructural.
- t-SNE revela vecindades de municipios con perfiles socioeconómicos similares, útil para segmentación y análisis comparativo.

> Nota: aquí se cumple hasta el **punto 3** de la práctica, dejando fuera la construcción formal del índice final (punto 4).