In [22]:
import os
import zipfile
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [24]:
dfs = {}

with zipfile.ZipFile("data/M3P1_Metodos_Reduccion.zip") as z:
    print("Archivos:")
    for name in z.namelist():
        
        if name.endswith("/"):
            continue

        base = os.path.basename(name)
        print(base)

        if base.endswith(".csv"):
            key = base.removesuffix(".csv")
            with z.open(name) as f:
                dfs[key] = pd.read_csv(f)

        elif base.endswith(".txt"):
            key = base.removesuffix(".txt")
            with z.open(name) as f:
                dfs[key] = pd.read_csv(f, sep="\t")

Archivos:
tam_loc.csv.csv
conjunto_de_datos_iter_00CSV20.csv

/var/folders/w3/5tjl2q2n0yn8r_8pkh98tr8m0000gn/T/ipykernel_12872/1409168344.py:16: DtypeWarning: Columns (0: ALTITUD) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[key] = pd.read_csv(f)

diccionario_datos_iter_00CSV20.csv
metadatos_iter_00_cpv2020.txt

In [26]:
for key in dfs.keys():
    print(key)
    display(dfs[key])

tam_loc.csv

    tam_loc                   descripcion
0         1            1 a 249 habitantes
1         2         250 a 499 habitantes
2         3          500 a 999 habitantes
3         4      1 000 a 2 499 habitantes
4         5      2 500 a 4 999 habitantes
5         6      5 000 a 9 999 habitantes
6         7    10 000 a 14 999 habitantes
7         8   15 000 a 29 999 habitantes
8         9    30 000 a 49 999 habitantes
9        10    50 000 a 99 999 habitantes
10       11  100 000 a 249 999 habitantes
11       12  250 000 a 499 999 habitantes
12       13  500 000 a 999 999 habitantes
13       14    1 000 000 y más habitantes

conjunto_de_datos_iter_00CSV20

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_3YMAS,P_3YMAS_F,P_3YMAS_M,P_5YMAS,P_5YMAS_F,P_5YMAS_M,P_12YMAS,P_12YMAS_F,P_12YMAS_M,P_15YMAS,P_15YMAS_F,P_15YMAS_M,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_3A5,P_3A5_F,P_3A5_M,P_6A11,P_6A11_F,P_6A11_M,P_8A14,P_8A14_F,P_8A14_M,P_12A14,P_12A14_F,P_12A14_M,P_15A17,P_15A17_F,P_15A17_M,P_18A24,P_18A24_F,P_18A24_M,P_15A49_F,P_60YMAS,P_60YMAS_F,P_60YMAS_M,REL_H_M,POB0_14,POB15_64,POB65_MAS,P_0A4,P_0A4_F,P_0A4_M,P_5A9,P_5A9_F,P_5A9_M,P_10A14,P_10A14_F,P_10A14_M,P_15A19,P_15A19_F,P_15A19_M,P_20A24,P_20A24_F,P_20A24_M,P_25A29,P_25A29_F,P_25A29_M,P_30A34,P_30A34_F,P_30A34_M,P_35A39,P_35A39_F,P_35A39_M,P_40A44,P_40A44_F,P_40A44_M,P_45A49,P_45A49_F,P_45A49_M,P_50A54,P_50A54_F,P_50A54_M,P_55A59,P_55A59_F,P_55A59_M,P_60A64,P_60A64_F,P_60A64_M,P_65A69,P_65A69_F,P_65A69_M,P_70A74,P_70A74_F,P_70A74_M,P_75A79,P_75A79_F,P_75A79_M,P_80A84,P_80A84_F,P_80A84_M,P_85YMAS,P_85YMAS_F,P_85YMAS_M,PROM_HNV,PNACENT,PNACENT_F,PNACENT_M,PNACOE,PNACOE_F,PNACOE_M,PRES2015,PRES2015_F,PRES2015_M,PRESOE15,PRESOE15_F,PRESOE15_M,P3YM_HLI,P3YM_HLI_F,P3YM_HLI_M,P3HLINHE,P3HLINHE_F,P3HLINHE_M,P3HLI_HE,P3HLI_HE_F,P3HLI_HE_M,P5_HLI,P5_HLI_NHE,P5_HLI_HE,PHOG_IND,POB_AFRO,POB_AFRO_F,POB_AFRO_M,PCON_DISC,PCDISC_MOT,PCDISC_VIS,PCDISC_LENG,PCDISC_AUD,PCDISC_MOT2,PCDISC_MEN,PCON_LIMI,PCLIM_CSB,PCLIM_VIS,PCLIM_HACO,PCLIM_OAUD,PCLIM_MOT2,PCLIM_RE_CO,PCLIM_PMEN,PSIND_LIM,P3A5_NOA,P3A5_NOA_F,P3A5_NOA_M,P6A11_NOA,P6A11_NOAF,P6A11_NOAM,P12A14NOA,P12A14NOAF,P12A14NOAM,P15A17A,P15A17A_F,P15A17A_M,P18A24A,P18A24A_F,P18A24A_M,P8A14AN,P8A14AN_F,P8A14AN_M,P15YM_AN,P15YM_AN_F,P15YM_AN_M,P15YM_SE,P15YM_SE_F,P15YM_SE_M,P15PRI_IN,P15PRI_INF,P15PRI_INM,P15PRI_CO,P15PRI_COF,P15PRI_COM,P15SEC_IN,P15SEC_INF,P15SEC_INM,P15SEC_CO,P15SEC_COF,P15SEC_COM,P18YM_PB,P18YM_PB_F,P18YM_PB_M,GRAPROES,GRAPROES_F,GRAPROES_M,PEA,PEA_F,PEA_M,PE_INAC,PE_INAC_F,PE_INAC_M,POCUPADA,POCUPADA_F,POCUPADA_M,PDESOCUP,PDESOCUP_F,PDESOCUP_M,PSINDER,PDER_SS,PDER_IMSS,PDER_ISTE,PDER_ISTEE,PAFIL_PDOM,PDER_SEGP,PDER_IMSSB,PAFIL_IPRIV,PAFIL_OTRAI,P12YM_SOLT,P12YM_CASA,P12YM_SEPA,PCATOLICA,PRO_CRIEVA,POTRAS_REL,PSIN_RELIG,TOTHOG,HOGJEF_F,HOGJEF_M,POBHOG,PHOGJEF_F,PHOGJEF_M,VIVTOT,TVIVHAB,TVIVPAR,VIVPAR_HAB,VIVPARH_CV,TVIVPARHAB,VIVPAR_DES,VIVPAR_UT,OCUPVIVPAR,PROM_OCUP,PRO_OCUP_C,VPH_PISODT,VPH_PISOTI,VPH_1DOR,VPH_2YMASD,VPH_1CUART,VPH_2CUART,VPH_3YMASC,VPH_C_ELEC,VPH_S_ELEC,VPH_AGUADV,VPH_AEASP,VPH_AGUAFV,VPH_TINACO,VPH_CISTER,VPH_EXCSA,VPH_LETR,VPH_DRENAJ,VPH_NODREN,VPH_C_SERV,VPH_NDEAED,VPH_DSADMA,VPH_NDACMM,VPH_SNBIEN,VPH_REFRI,VPH_LAVAD,VPH_HMICRO,VPH_AUTOM,VPH_MOTO,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC,TAMLOC
0,0,Total nacional,0,Total nacional,0,Total nacional,NaN,NaN,NaN,126014024,64540634,61473390,5764054,2848875,2915179,119976584,61554567,58422017,115693273,59433559,56259714,100528155,51962264,48565891,93985354,48732991,45252363,87492680,45530857,41961823,6462212,3193548,3268664,12986217,6398755,6587462,15287375,7531118,7756257,6542801,3229273,3313528,6492674,3202134,3290540,14736111,7398617,7337494,33885546,15142976,8139094,7003882,95.25,31755284,83663440,10321914,10047365,4969883,5077482,10764379,5311288,5453091,10943540,5389280,5554260,10806690,5344540,5462150,10422095,5256211,5165884,9993001,5131597,4861404,9420827,4893101,4527726,9020276,4688746,4331530,8503586,4441282,4062304,7942413,4130069,3812344,7037532,3705369,3332163,5695958,3002982,2692976,4821062,2563200,2257862,3645077,1938227,1706850,2647340,1413848,1233492,1814582,966684,847898,1175364,651552,523812,1039551,605583,433968,2.09,102724322,52519974,50204348,21611963,11222300,10389663,111075594,57288776,53786818,3807844,1889986,1917858,7364645,3783447,3581198,865972,547528,318444,6423548,3198595,3224953,7177185,785361,6317027,11800247,2576213,1297617,1278596,6179890,2939986,2691338,945162,1350802,1168098,1149257,13934448,4365234,8974853,864662,2900108,673540,2698640,1590583,104815785,2359716,1155636,1204080,577029,275189,301840,618233,283195,335038,4726359,2390407,2335952,4894125,2482980,2411145,412725,178152,234573,4456431,2677192,1779239,4841952,2791237,2050715,7731820,4042527,3689293,12325433,6515268,5810165,2913915,1297269,1616646,22833912,11857736,10976176,39977750,20408275,19569475,9.74,9.64,9.84,62281634,25465693,36815941,37891261,26379060,11512201,61121324,25137019,35984305,1160310,328674,831636,32999713,92582812,47245909,7165164,1041534,1192255,32842765,958787,2615213,1149542,34370381,54036478,12049313,97864218,14095307,248169,13314516,35219141,11474983,23744158,125514839,37418569,88096270,43903443,35233462,42300700,33630719,35156897,35219141,6155682,2514299,125514839,3.56,0.96,33833470,1235550,11186214,23887498,2085925,5460133,27527131,34805976,268863,33858339,29541708,1215497,22629812,9652823,33081729,1396774,33564054,1498766,32671764,79584,32979844,16874580,581095,30811260,25610544,16651199,16340788,4227460,7469168,23772973,32031555,13204680,13184550,30775898,18307193,15211306,6616141,4047100,1788552,3170894,15108204,852871,*
1,0,Total nacional,0,Total nacional,9998,Localidades de una vivienda,NaN,NaN,NaN,250354,96869,153485,10493,5193,5300,239441,91463,147978,232086,87931,144155,207748,76111,131637,197411,71344,126067,186968,66514,120454,10900,5270,5630,20793,10082,10711,24342,11538,12804,10337,4767,5570,10443,4830,5613,27841,11140,16701,47693,37383,13442,23941,158.45,52523,171209,26202,17848,8725,9123,17380,8526,8854,17295,8061,9234,18303,8138,10165,19981,7832,12149,20584,7125,13459,19601,6309,13292,18645,6289,12356,17934,6060,11874,16840,5940,10900,15070,5481,9589,13070,4728,8342,11181,4050,7131,9160,3343,5817,6903,2421,4482,4765,1639,3126,3017,1081,1936,2357,908,1449,*,177757,75977,101780,54046,18910,35136,184423,79893,104530,16172,6089,10083,26486,10908,15578,2712,1652,1060,22906,9203,13703,25743,2412,22464,27252,4122,1614,2508,12126,5875,5008,1940,2895,2123,2179,28067,10653,17059,2092,6916,1625,5763,2823,207052,5620,2689,2931,2920,1403,1517,2699,1190,1509,4952,2386,2566,4157,1610,2547,2393,1080,1313,24331,10532,13799,28014,11278,16736,38545,13056,25489,38809,14762,24047,14833,3143,11690,40180,15578,24602,33907,11972,21935,6.5,6.51,6.5,128289,33067,95222,68766,42827,25939,127469,32906,94563,820,161,659,86676,153663,53559,3795,552,649,84849,2883,3288,6284,63913,124916,18433,187464,29725,1117,29624,62516,8292,54224,198544,28805,169739,101390,62767,99591,60968,62091,62516,18117,20506,198544,3.18,1.03,53169,8797,30115,31851,7333,16206,38424,48426,13538,45470,8198,16498,34143,13743,44688,9825,47253,14708,35091,4842,43668,24373,5136,38199,26412,13608,30940,15001,13600,36738,40001,5797,3523,47005,8385,18981,1732,1113,12775,14143,51293,7154,*
2,0,Total nacional,0,Total nacional,9999,Localidades de dos viviendas,NaN,NaN,NaN,147125,61324,85801,6798,3407,3391,139757,57628,82129,135028,55256,79772,119223,47543,71680,111530,44275,67255,104612,41184,63428,7028,3511,3517,13506,6574,6932,16724,7679,9045,7693,3268,4425,6918,3091,3827,16336,6760,9576,29297,21277,8916,12361,139.91,35025,96250,15280,11527,5779,5748,11274,5558,5716,12224,5423,6801,11484,5140,6344,11770,4711,7059,12238,4427,7811,11315,4074,7241,10357,3825,6532,9705,3743,5962,8668,3377,5291,7878,3239,4639,6838,2823,4015,5997,2511,3486,5052,2130,2922,3852,1575,2277,2920,1182,1738,1868,793,1075,1588,725,863,*,117805,52686,65119,20274,7205,13069,114178,52604,61574,6214,1664,4550,18640,8181,10459,3098,1901,1197,14758,6205,8553,17992,2742,14467,21531,2816,1056,1760,8058,4079,3590,1664,2295,1808,1825,16685,6309,10523,1279,3982,1085,3479,1579,120888,3783,1873,1910,1782,874,908,1674,766,908,3557,1509,2048,2738,1053,1685,1527,712,815,15092,7074,8018,17660,7476,10184,21620,8064,13556,22033,9009,13024,5040,1561,3479,24056,9485,14571,19102,7672,11430,6.45,6.48,6.43,68904,18475,50429,46162,28959,17203,68215,18365,49850,689,110,579,56232,90057,23569,2312,350,485,59445,1956,1300,1504,38355,68874,10660,112351,16630,675,16432,36568,6620,29948,125099,21860,103239,61435,36676,60317,35558,36359,36568,12225,12534,125099,3.42,1.03,29302,6891,17038,19157,4351,9491,22351,28586,7607,26499,5054,9696,18089,7029,24348,6050,26036,10155,19807,2935,23841,16122,4115,21775,15880,7902,16699,8076,6330,20009,23198,3588,2177,25581,5027,11306,971,708,8247,10065,29741,5283,*
3,1,Aguascalientes,0,Total de la entidad Aguascalientes,0,Total de la Entidad,NaN,NaN,NaN,1425607,728924,696683,71864,35604,36260,1352235,692561,659674,1299669,666713,632956,1116719,576593,540126,1038904,538387,500517,960764,500089,460675,78833,38679,40154,156683,77289,79394,181905,89383,92522,77815,38206,39609,78140,38298,39842,180847,90632,90215,388917,145376,78703,66673,95.58,385195,941834,97070,124430,61452,62978,131048,64689,66359,129717,63637,66080,131967,65064,66903,127020,63866,63154,118426,60285,58141,106825,55174,51651,99257,51483,47774,92378,48539,43839,84669,44506,40163,74121,39510,34611,58865,31257,27608,48306,25871,22435,35823,19125,16698,25586,13804,11782,16581,8842,7739,10186,5789,4397,8894,5272,3622,2.11,1133247,576781,556466,276430,144420,132010,1232234,635320,596914,56422,27956,28466,2539,1043,1496,25,13,12,2461,1012,1449,2508,22,2437,5552,22425,11211,11214,71294,34507,29888,9297,12989,12726,12967,165482,49636,103289,8940,30298,6368,34556,20169,1177938,31495,15371,16124,4941,2292,2649,6812,2901,3911,55493,28286,27207,59978,31114,28864,3178,1318,1860,21908,11762,10146,25567,13286,12281,65609,33542,32067,122405,64730,57675,30347,12806,17541,288036,151759,136277,467249,240419,226830,10.35,10.32,10.38,706930,293533,413397,407903,282320,125583,692983,289268,403715,13947,4265,9682,262088,1161139,780525,92771,3786,3196,271996,1680,31789,3179,402370,593273,120740,1272419,73359,1900,74439,386445,119453,266992,1421200,395735,1025465,463972,386671,453099,375798,386011,386445,60327,16974,1421200,3.68,0.89,382634,2899,86423,299141,6390,30686,348487,384361,1210,383430,355192,2137,295903,152521,382597,1011,383148,2379,380982,184,382121,130744,876,365189,335710,238571,240381,45642,105752,312002,370411,177149,147818,359895,236003,174089,98724,70126,6021,15323,128996,1711,*
4,1,Aguascalientes,0,Total de la entidad Aguascalientes,9998,Localidades de una vivienda,NaN,NaN,NaN,3697,1510,2187,165,81,84,3532,1429,2103,3420,1377,2043,3018,1179,1839,2836,1086,1750,2609,987,1622,169,80,89,345,170,175,427,211,216,182,93,89,227,99,128,438,180,258,750,448,190,258,144.83,861,2524,312,277,133,144,281,142,139,303,149,154,348,148,200,317,131,186,300,109,191,280,89,191,272,85,187,259,103,156,238,85,153,177,72,105,197,74,123,136,54,82,106,44,62,78,35,43,58,26,32,38,19,19,32,12,20,*,2908,1216,1692,749,275,474,2721,1298,1423,152,69,83,20,3,17,0,0,0,15,3,12,20,0,15,5,52,20,32,212,110,69,18,39,38,27,418,161,226,30,75,24,95,56,3044,84,36,48,25,17,8,34,16,18,133,53,80,93,33,60,19,10,9,180,78,102,209,79,130,378,152,226,470,207,263,157,37,120,832,291,541,722,289,433,8.14,8.2,8.11,2077,506,1571,939,673,266,2060,497,1563,17,9,8,1067,2472,1090,113,4,0,1242,2,31,13,1037,1695,285,3250,223,11,195,807,123,684,3137,532,2605,1368,813,1354,799,801,807,233,322,3137,3.89,1.02,771,30,270,531,39,116,646,723,78,694,195,107,608,405,708,27,719,82,610,16,704,203,12,632,561,276,529,216,407,650,684,167,43,732,205,212,48,41,39,62,530,20,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195657,32,Zacatecas,58,Santa María de la Paz,37,Mesa Grande,"103°24'52.925"" W","21°33'12.375"" N",1944.0,165,88,77,5,4,1,160,84,76,154,82,72,133,72,61,125,67,58,110,60,50,7,3,4,20,9,11,20,8,12,8,5,3,15,7,8,14,11,3,43,36,18,18,87.5,40,96,29,11,6,5,14,9,5,15,6,9,21,11,10,8,7,1,4,2,2,11,6,5,13,6,7,11,4,7,8,7,1,5,1,4,8,5,3,7,3,4,3,3,0,7,3,4,9,4,5,6,4,2,4,1,3,3.96,161,84,77,3,3,0,153,82,71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,3,2,2,2,3,4,17,3,13,2,3,1,1,4,139,3,1,2,0,0,0,1,0,1,11,6,5,1,1,0,0,0,0,3,2,1,5,3,2,40,20,20,22,11,11,8,1,7,32,21,11,11,5,6,6.51,6.7,6.29,38,4,34,93,68,25,38,4,34,0,0,0,17,148,35,0,0,0,110,1,4,0,48,76,9,165,0,0,0,49,17,32,165,46,119,80,49,80,49,49,49,25,6,165,3.37,1.02,45,4,21,28,2,10,37,49,0,49,46,0,46,13,34,15,39,10,39,0,34,15,0,49,43,18,26,23,12,29,44,6,29,24,9,13,0,0,3,9,38,1,1
195658,32,Zacatecas,58,Santa María de la Paz,39,San Isidro,"103°20'14.164"" W","21°29'11.130"" N",2031.0,1,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,1,1,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,1
195659,32,Zacatecas,58,Santa María de la Paz,41,San Miguel Tepetitlán,"103°20'09.356"" W","21°30'15.168"" N",1977.0,97,50,47,1,0,1,96,50,46,93,48,45,76,37,39,69,34,35,65,31,34,4,3,1,16,10,6,16,8,8,7,3,4,4,3,1,1,0,1,16,27,13,14,94,28,45,24,4,2,2,13,9,4,11,5,6,4,3,1,1,0,1,2,1,1,7,5,2,8,4,4,5,1,4,5,2,3,7,4,3,3,1,2,3,1,2,3,2,1,10,4,6,6,2,4,3,2,1,2,2,0,4.3,85,45,40,8,3,5,88,45,43,3,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,1,1,1,1,2,21,6,12,3,6,4,9,1,73,0,0,0,0,0,0,0,0,0,3,2,1,0,0,0,0,0,0,9,2,7,5,2,3,19,9,10,9,3,6,0,0,0,24,15,9,11,4,7,7.22,7.41,7.03,34,6,28,42,31,11,33,6,27,1,0,1,28,69,10,0,0,0,59,0,0,0,20,50,6,97,0,0,0,31,4,27,97,11,86,56,31,56,31,31,31,20,5,97,3.13,0.76,31,0,10,21,0,2,29,31,0,30,0,1,28,9,27,3,27,4,27,0,27,11,0,30,23,17,20,7,5,20,26,4,1,21,12,21,1,1,1,10,19,0,1
195660,32,Zacatecas,58,Santa María de la Paz,42,San Rafael,"103°22'20.134"" W","21°31'39.341"" N",2042.0,3,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,1,1,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,1
195661,32,Zacatecas,58,Santa María de la Paz,9998,Localidades de una vivienda,NaN,NaN,NaN,32,11,21,1,0,1,31,11,20,30,10,20,27,10,17,23,7,16,23,7,16,1,1,0,3,0,3,6,3,3,4,3,1,0,0,0,3,1,2,5,7,2,5,190.91,9,18,5,2,1,1,1,0,1,6,3,3,1,0,1,2,1,1,0,0,0,2,1,1,4,1,3,1,1,0,3,1,2,3,0,3,0,0,0,2,1,1,1,0,1,1,1,0,0,0,0,1,0,1,2,0,2,*,26,7,19,3,2,1,24,8,16,2,1,1,2,1,1,0,0,0,2,1,1,2,0,2,8,0,0,0,1,1,0,1,0,1,1,5,4,4,1,4,1,3,1,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,3,2,0,2,6,1,5,3,0,3,2,2,0,7,3,4,3,1,2,6.76,9.33,5.73,17,4,13,10,6,4,14,4,10,3,0,3,5,26,0,4,0,0,18,4,0,0,9,13,5,31,0,0,0,9,1,8,32,2,30,26,9,26,9,9,9,15,2,32,3.56,0.8,7,2,3,6,0,0,9,8,1,9,1,0,9,3,8,0,8,1,7,0,8,2,1,5,3,3,7,3,2,5,8,2,0,7,2,6,1,1,1,2,7,1,*

diccionario_datos_iter_00CSV20

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,CENSO DE POBLACIÓN Y VIVIENDA 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Relación de indicadores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Cuarta edición,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Núm.,Indicador,Descripción,Mnemónico,Rangos,Longitud,NaN,NaN,NaN,NaN
4,1,Clave de entidad federativa,Código que identifica a la entidad federativa....,ENTIDAD,00…32,2,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
285,273,Viviendas particulares habitadas sin radio ni ...,Viviendas particulares habitadas que no cuenta...,VPH_SINRTV,0…999999999,9,NaN,NaN,NaN,NaN
286,274,Viviendas particulares habitadas sin línea tel...,Viviendas particulares habitadas que no cuenta...,VPH_SINLTC,0…999999999,9,NaN,NaN,NaN,NaN
287,275,Viviendas particulares habitadas sin computado...,Viviendas particulares habitadas que no cuenta...,VPH_SINCINT,0…999999999,9,NaN,NaN,NaN,NaN
288,276,Viviendas particulares habitadas sin tecnologí...,Viviendas particulares habitadas que no cuenta...,VPH_SINTIC,0…999999999,9,NaN,NaN,NaN,NaN
289,277,Tamaño de localidad,Total de personas que residen habitualmente en...,TAMLOC,01..14,2,NaN,NaN,NaN,NaN

metadatos_iter_00_cpv2020

               identifier: MEX-INEGI.ESD2.01-CPV-2020
0   title: Principales resultados por localidad (I...
1                                       description:
2   INEGI. Censo de Población y Vivienda 2020. SNI...
3   Conjunto de indicadores de población y viviend...
4                                               NOTA:
5   El 16 de marzo de 2021, se reemplazó el archiv...
6   El 16 de abril de 2021, se reemplazó el archiv...
7   El 26 de julio de 2021, se reemplazó el archiv...
8   El 19 de mayo de 2022, se reemplazó el archivo...
9                                modified: 2022-05-19
10  publisher: Instituto Nacional de Estadística y...
11               mbox: atencion.usuarios@inegi.org.mx
12  license: https://www.inegi.org.mx/inegi/termin...
13  dataDictionary: https://www.inegi.org.mx/rnm/i...
14  keyword: “vivienda", "personas", "censo", "ite...
15  contactPoint: Mtro. J. Armando Aguiar Rodrígue...
16                    temporal: 2020-03-15-2020-03-15
17                  spatial: Estados Unidos Mexicanos
18                   accrualPeriodicity: Decenalmente
19  distribution: https://www.inegi.org.mx/program...

In [27]:
display(dfs["conjunto_de_datos_iter_00CSV20"])

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_3YMAS,P_3YMAS_F,P_3YMAS_M,P_5YMAS,P_5YMAS_F,P_5YMAS_M,P_12YMAS,P_12YMAS_F,P_12YMAS_M,P_15YMAS,P_15YMAS_F,P_15YMAS_M,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_3A5,P_3A5_F,P_3A5_M,P_6A11,P_6A11_F,P_6A11_M,P_8A14,P_8A14_F,P_8A14_M,P_12A14,P_12A14_F,P_12A14_M,P_15A17,P_15A17_F,P_15A17_M,P_18A24,P_18A24_F,P_18A24_M,P_15A49_F,P_60YMAS,P_60YMAS_F,P_60YMAS_M,REL_H_M,POB0_14,POB15_64,POB65_MAS,P_0A4,P_0A4_F,P_0A4_M,P_5A9,P_5A9_F,P_5A9_M,P_10A14,P_10A14_F,P_10A14_M,P_15A19,P_15A19_F,P_15A19_M,P_20A24,P_20A24_F,P_20A24_M,P_25A29,P_25A29_F,P_25A29_M,P_30A34,P_30A34_F,P_30A34_M,P_35A39,P_35A39_F,P_35A39_M,P_40A44,P_40A44_F,P_40A44_M,P_45A49,P_45A49_F,P_45A49_M,P_50A54,P_50A54_F,P_50A54_M,P_55A59,P_55A59_F,P_55A59_M,P_60A64,P_60A64_F,P_60A64_M,P_65A69,P_65A69_F,P_65A69_M,P_70A74,P_70A74_F,P_70A74_M,P_75A79,P_75A79_F,P_75A79_M,P_80A84,P_80A84_F,P_80A84_M,P_85YMAS,P_85YMAS_F,P_85YMAS_M,PROM_HNV,PNACENT,PNACENT_F,PNACENT_M,PNACOE,PNACOE_F,PNACOE_M,PRES2015,PRES2015_F,PRES2015_M,PRESOE15,PRESOE15_F,PRESOE15_M,P3YM_HLI,P3YM_HLI_F,P3YM_HLI_M,P3HLINHE,P3HLINHE_F,P3HLINHE_M,P3HLI_HE,P3HLI_HE_F,P3HLI_HE_M,P5_HLI,P5_HLI_NHE,P5_HLI_HE,PHOG_IND,POB_AFRO,POB_AFRO_F,POB_AFRO_M,PCON_DISC,PCDISC_MOT,PCDISC_VIS,PCDISC_LENG,PCDISC_AUD,PCDISC_MOT2,PCDISC_MEN,PCON_LIMI,PCLIM_CSB,PCLIM_VIS,PCLIM_HACO,PCLIM_OAUD,PCLIM_MOT2,PCLIM_RE_CO,PCLIM_PMEN,PSIND_LIM,P3A5_NOA,P3A5_NOA_F,P3A5_NOA_M,P6A11_NOA,P6A11_NOAF,P6A11_NOAM,P12A14NOA,P12A14NOAF,P12A14NOAM,P15A17A,P15A17A_F,P15A17A_M,P18A24A,P18A24A_F,P18A24A_M,P8A14AN,P8A14AN_F,P8A14AN_M,P15YM_AN,P15YM_AN_F,P15YM_AN_M,P15YM_SE,P15YM_SE_F,P15YM_SE_M,P15PRI_IN,P15PRI_INF,P15PRI_INM,P15PRI_CO,P15PRI_COF,P15PRI_COM,P15SEC_IN,P15SEC_INF,P15SEC_INM,P15SEC_CO,P15SEC_COF,P15SEC_COM,P18YM_PB,P18YM_PB_F,P18YM_PB_M,GRAPROES,GRAPROES_F,GRAPROES_M,PEA,PEA_F,PEA_M,PE_INAC,PE_INAC_F,PE_INAC_M,POCUPADA,POCUPADA_F,POCUPADA_M,PDESOCUP,PDESOCUP_F,PDESOCUP_M,PSINDER,PDER_SS,PDER_IMSS,PDER_ISTE,PDER_ISTEE,PAFIL_PDOM,PDER_SEGP,PDER_IMSSB,PAFIL_IPRIV,PAFIL_OTRAI,P12YM_SOLT,P12YM_CASA,P12YM_SEPA,PCATOLICA,PRO_CRIEVA,POTRAS_REL,PSIN_RELIG,TOTHOG,HOGJEF_F,HOGJEF_M,POBHOG,PHOGJEF_F,PHOGJEF_M,VIVTOT,TVIVHAB,TVIVPAR,VIVPAR_HAB,VIVPARH_CV,TVIVPARHAB,VIVPAR_DES,VIVPAR_UT,OCUPVIVPAR,PROM_OCUP,PRO_OCUP_C,VPH_PISODT,VPH_PISOTI,VPH_1DOR,VPH_2YMASD,VPH_1CUART,VPH_2CUART,VPH_3YMASC,VPH_C_ELEC,VPH_S_ELEC,VPH_AGUADV,VPH_AEASP,VPH_AGUAFV,VPH_TINACO,VPH_CISTER,VPH_EXCSA,VPH_LETR,VPH_DRENAJ,VPH_NODREN,VPH_C_SERV,VPH_NDEAED,VPH_DSADMA,VPH_NDACMM,VPH_SNBIEN,VPH_REFRI,VPH_LAVAD,VPH_HMICRO,VPH_AUTOM,VPH_MOTO,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC,TAMLOC
0,0,Total nacional,0,Total nacional,0,Total nacional,NaN,NaN,NaN,126014024,64540634,61473390,5764054,2848875,2915179,119976584,61554567,58422017,115693273,59433559,56259714,100528155,51962264,48565891,93985354,48732991,45252363,87492680,45530857,41961823,6462212,3193548,3268664,12986217,6398755,6587462,15287375,7531118,7756257,6542801,3229273,3313528,6492674,3202134,3290540,14736111,7398617,7337494,33885546,15142976,8139094,7003882,95.25,31755284,83663440,10321914,10047365,4969883,5077482,10764379,5311288,5453091,10943540,5389280,5554260,10806690,5344540,5462150,10422095,5256211,5165884,9993001,5131597,4861404,9420827,4893101,4527726,9020276,4688746,4331530,8503586,4441282,4062304,7942413,4130069,3812344,7037532,3705369,3332163,5695958,3002982,2692976,4821062,2563200,2257862,3645077,1938227,1706850,2647340,1413848,1233492,1814582,966684,847898,1175364,651552,523812,1039551,605583,433968,2.09,102724322,52519974,50204348,21611963,11222300,10389663,111075594,57288776,53786818,3807844,1889986,1917858,7364645,3783447,3581198,865972,547528,318444,6423548,3198595,3224953,7177185,785361,6317027,11800247,2576213,1297617,1278596,6179890,2939986,2691338,945162,1350802,1168098,1149257,13934448,4365234,8974853,864662,2900108,673540,2698640,1590583,104815785,2359716,1155636,1204080,577029,275189,301840,618233,283195,335038,4726359,2390407,2335952,4894125,2482980,2411145,412725,178152,234573,4456431,2677192,1779239,4841952,2791237,2050715,7731820,4042527,3689293,12325433,6515268,5810165,2913915,1297269,1616646,22833912,11857736,10976176,39977750,20408275,19569475,9.74,9.64,9.84,62281634,25465693,36815941,37891261,26379060,11512201,61121324,25137019,35984305,1160310,328674,831636,32999713,92582812,47245909,7165164,1041534,1192255,32842765,958787,2615213,1149542,34370381,54036478,12049313,97864218,14095307,248169,13314516,35219141,11474983,23744158,125514839,37418569,88096270,43903443,35233462,42300700,33630719,35156897,35219141,6155682,2514299,125514839,3.56,0.96,33833470,1235550,11186214,23887498,2085925,5460133,27527131,34805976,268863,33858339,29541708,1215497,22629812,9652823,33081729,1396774,33564054,1498766,32671764,79584,32979844,16874580,581095,30811260,25610544,16651199,16340788,4227460,7469168,23772973,32031555,13204680,13184550,30775898,18307193,15211306,6616141,4047100,1788552,3170894,15108204,852871,*
1,0,Total nacional,0,Total nacional,9998,Localidades de una vivienda,NaN,NaN,NaN,250354,96869,153485,10493,5193,5300,239441,91463,147978,232086,87931,144155,207748,76111,131637,197411,71344,126067,186968,66514,120454,10900,5270,5630,20793,10082,10711,24342,11538,12804,10337,4767,5570,10443,4830,5613,27841,11140,16701,47693,37383,13442,23941,158.45,52523,171209,26202,17848,8725,9123,17380,8526,8854,17295,8061,9234,18303,8138,10165,19981,7832,12149,20584,7125,13459,19601,6309,13292,18645,6289,12356,17934,6060,11874,16840,5940,10900,15070,5481,9589,13070,4728,8342,11181,4050,7131,9160,3343,5817,6903,2421,4482,4765,1639,3126,3017,1081,1936,2357,908,1449,*,177757,75977,101780,54046,18910,35136,184423,79893,104530,16172,6089,10083,26486,10908,15578,2712,1652,1060,22906,9203,13703,25743,2412,22464,27252,4122,1614,2508,12126,5875,5008,1940,2895,2123,2179,28067,10653,17059,2092,6916,1625,5763,2823,207052,5620,2689,2931,2920,1403,1517,2699,1190,1509,4952,2386,2566,4157,1610,2547,2393,1080,1313,24331,10532,13799,28014,11278,16736,38545,13056,25489,38809,14762,24047,14833,3143,11690,40180,15578,24602,33907,11972,21935,6.5,6.51,6.5,128289,33067,95222,68766,42827,25939,127469,32906,94563,820,161,659,86676,153663,53559,3795,552,649,84849,2883,3288,6284,63913,124916,18433,187464,29725,1117,29624,62516,8292,54224,198544,28805,169739,101390,62767,99591,60968,62091,62516,18117,20506,198544,3.18,1.03,53169,8797,30115,31851,7333,16206,38424,48426,13538,45470,8198,16498,34143,13743,44688,9825,47253,14708,35091,4842,43668,24373,5136,38199,26412,13608,30940,15001,13600,36738,40001,5797,3523,47005,8385,18981,1732,1113,12775,14143,51293,7154,*
2,0,Total nacional,0,Total nacional,9999,Localidades de dos viviendas,NaN,NaN,NaN,147125,61324,85801,6798,3407,3391,139757,57628,82129,135028,55256,79772,119223,47543,71680,111530,44275,67255,104612,41184,63428,7028,3511,3517,13506,6574,6932,16724,7679,9045,7693,3268,4425,6918,3091,3827,16336,6760,9576,29297,21277,8916,12361,139.91,35025,96250,15280,11527,5779,5748,11274,5558,5716,12224,5423,6801,11484,5140,6344,11770,4711,7059,12238,4427,7811,11315,4074,7241,10357,3825,6532,9705,3743,5962,8668,3377,5291,7878,3239,4639,6838,2823,4015,5997,2511,3486,5052,2130,2922,3852,1575,2277,2920,1182,1738,1868,793,1075,1588,725,863,*,117805,52686,65119,20274,7205,13069,114178,52604,61574,6214,1664,4550,18640,8181,10459,3098,1901,1197,14758,6205,8553,17992,2742,14467,21531,2816,1056,1760,8058,4079,3590,1664,2295,1808,1825,16685,6309,10523,1279,3982,1085,3479,1579,120888,3783,1873,1910,1782,874,908,1674,766,908,3557,1509,2048,2738,1053,1685,1527,712,815,15092,7074,8018,17660,7476,10184,21620,8064,13556,22033,9009,13024,5040,1561,3479,24056,9485,14571,19102,7672,11430,6.45,6.48,6.43,68904,18475,50429,46162,28959,17203,68215,18365,49850,689,110,579,56232,90057,23569,2312,350,485,59445,1956,1300,1504,38355,68874,10660,112351,16630,675,16432,36568,6620,29948,125099,21860,103239,61435,36676,60317,35558,36359,36568,12225,12534,125099,3.42,1.03,29302,6891,17038,19157,4351,9491,22351,28586,7607,26499,5054,9696,18089,7029,24348,6050,26036,10155,19807,2935,23841,16122,4115,21775,15880,7902,16699,8076,6330,20009,23198,3588,2177,25581,5027,11306,971,708,8247,10065,29741,5283,*
3,1,Aguascalientes,0,Total de la entidad Aguascalientes,0,Total de la Entidad,NaN,NaN,NaN,1425607,728924,696683,71864,35604,36260,1352235,692561,659674,1299669,666713,632956,1116719,576593,540126,1038904,538387,500517,960764,500089,460675,78833,38679,40154,156683,77289,79394,181905,89383,92522,77815,38206,39609,78140,38298,39842,180847,90632,90215,388917,145376,78703,66673,95.58,385195,941834,97070,124430,61452,62978,131048,64689,66359,129717,63637,66080,131967,65064,66903,127020,63866,63154,118426,60285,58141,106825,55174,51651,99257,51483,47774,92378,48539,43839,84669,44506,40163,74121,39510,34611,58865,31257,27608,48306,25871,22435,35823,19125,16698,25586,13804,11782,16581,8842,7739,10186,5789,4397,8894,5272,3622,2.11,1133247,576781,556466,276430,144420,132010,1232234,635320,596914,56422,27956,28466,2539,1043,1496,25,13,12,2461,1012,1449,2508,22,2437,5552,22425,11211,11214,71294,34507,29888,9297,12989,12726,12967,165482,49636,103289,8940,30298,6368,34556,20169,1177938,31495,15371,16124,4941,2292,2649,6812,2901,3911,55493,28286,27207,59978,31114,28864,3178,1318,1860,21908,11762,10146,25567,13286,12281,65609,33542,32067,122405,64730,57675,30347,12806,17541,288036,151759,136277,467249,240419,226830,10.35,10.32,10.38,706930,293533,413397,407903,282320,125583,692983,289268,403715,13947,4265,9682,262088,1161139,780525,92771,3786,3196,271996,1680,31789,3179,402370,593273,120740,1272419,73359,1900,74439,386445,119453,266992,1421200,395735,1025465,463972,386671,453099,375798,386011,386445,60327,16974,1421200,3.68,0.89,382634,2899,86423,299141,6390,30686,348487,384361,1210,383430,355192,2137,295903,152521,382597,1011,383148,2379,380982,184,382121,130744,876,365189,335710,238571,240381,45642,105752,312002,370411,177149,147818,359895,236003,174089,98724,70126,6021,15323,128996,1711,*
4,1,Aguascalientes,0,Total de la entidad Aguascalientes,9998,Localidades de una vivienda,NaN,NaN,NaN,3697,1510,2187,165,81,84,3532,1429,2103,3420,1377,2043,3018,1179,1839,2836,1086,1750,2609,987,1622,169,80,89,345,170,175,427,211,216,182,93,89,227,99,128,438,180,258,750,448,190,258,144.83,861,2524,312,277,133,144,281,142,139,303,149,154,348,148,200,317,131,186,300,109,191,280,89,191,272,85,187,259,103,156,238,85,153,177,72,105,197,74,123,136,54,82,106,44,62,78,35,43,58,26,32,38,19,19,32,12,20,*,2908,1216,1692,749,275,474,2721,1298,1423,152,69,83,20,3,17,0,0,0,15,3,12,20,0,15,5,52,20,32,212,110,69,18,39,38,27,418,161,226,30,75,24,95,56,3044,84,36,48,25,17,8,34,16,18,133,53,80,93,33,60,19,10,9,180,78,102,209,79,130,378,152,226,470,207,263,157,37,120,832,291,541,722,289,433,8.14,8.2,8.11,2077,506,1571,939,673,266,2060,497,1563,17,9,8,1067,2472,1090,113,4,0,1242,2,31,13,1037,1695,285,3250,223,11,195,807,123,684,3137,532,2605,1368,813,1354,799,801,807,233,322,3137,3.89,1.02,771,30,270,531,39,116,646,723,78,694,195,107,608,405,708,27,719,82,610,16,704,203,12,632,561,276,529,216,407,650,684,167,43,732,205,212,48,41,39,62,530,20,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195657,32,Zacatecas,58,Santa María de la Paz,37,Mesa Grande,"103°24'52.925"" W","21°33'12.375"" N",1944.0,165,88,77,5,4,1,160,84,76,154,82,72,133,72,61,125,67,58,110,60,50,7,3,4,20,9,11,20,8,12,8,5,3,15,7,8,14,11,3,43,36,18,18,87.5,40,96,29,11,6,5,14,9,5,15,6,9,21,11,10,8,7,1,4,2,2,11,6,5,13,6,7,11,4,7,8,7,1,5,1,4,8,5,3,7,3,4,3,3,0,7,3,4,9,4,5,6,4,2,4,1,3,3.96,161,84,77,3,3,0,153,82,71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,3,2,2,2,3,4,17,3,13,2,3,1,1,4,139,3,1,2,0,0,0,1,0,1,11,6,5,1,1,0,0,0,0,3,2,1,5,3,2,40,20,20,22,11,11,8,1,7,32,21,11,11,5,6,6.51,6.7,6.29,38,4,34,93,68,25,38,4,34,0,0,0,17,148,35,0,0,0,110,1,4,0,48,76,9,165,0,0,0,49,17,32,165,46,119,80,49,80,49,49,49,25,6,165,3.37,1.02,45,4,21,28,2,10,37,49,0,49,46,0,46,13,34,15,39,10,39,0,34,15,0,49,43,18,26,23,12,29,44,6,29,24,9,13,0,0,3,9,38,1,1
195658,32,Zacatecas,58,Santa María de la Paz,39,San Isidro,"103°20'14.164"" W","21°29'11.130"" N",2031.0,1,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,1,1,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,1
195659,32,Zacatecas,58,Santa María de la Paz,41,San Miguel Tepetitlán,"103°20'09.356"" W","21°30'15.168"" N",1977.0,97,50,47,1,0,1,96,50,46,93,48,45,76,37,39,69,34,35,65,31,34,4,3,1,16,10,6,16,8,8,7,3,4,4,3,1,1,0,1,16,27,13,14,94,28,45,24,4,2,2,13,9,4,11,5,6,4,3,1,1,0,1,2,1,1,7,5,2,8,4,4,5,1,4,5,2,3,7,4,3,3,1,2,3,1,2,3,2,1,10,4,6,6,2,4,3,2,1,2,2,0,4.3,85,45,40,8,3,5,88,45,43,3,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,1,1,1,1,2,21,6,12,3,6,4,9,1,73,0,0,0,0,0,0,0,0,0,3,2,1,0,0,0,0,0,0,9,2,7,5,2,3,19,9,10,9,3,6,0,0,0,24,15,9,11,4,7,7.22,7.41,7.03,34,6,28,42,31,11,33,6,27,1,0,1,28,69,10,0,0,0,59,0,0,0,20,50,6,97,0,0,0,31,4,27,97,11,86,56,31,56,31,31,31,20,5,97,3.13,0.76,31,0,10,21,0,2,29,31,0,30,0,1,28,9,27,3,27,4,27,0,27,11,0,30,23,17,20,7,5,20,26,4,1,21,12,21,1,1,1,10,19,0,1
195660,32,Zacatecas,58,Santa María de la Paz,42,San Rafael,"103°22'20.134"" W","21°31'39.341"" N",2042.0,3,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,1,1,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,1
195661,32,Zacatecas,58,Santa María de la Paz,9998,Localidades de una vivienda,NaN,NaN,NaN,32,11,21,1,0,1,31,11,20,30,10,20,27,10,17,23,7,16,23,7,16,1,1,0,3,0,3,6,3,3,4,3,1,0,0,0,3,1,2,5,7,2,5,190.91,9,18,5,2,1,1,1,0,1,6,3,3,1,0,1,2,1,1,0,0,0,2,1,1,4,1,3,1,1,0,3,1,2,3,0,3,0,0,0,2,1,1,1,0,1,1,1,0,0,0,0,1,0,1,2,0,2,*,26,7,19,3,2,1,24,8,16,2,1,1,2,1,1,0,0,0,2,1,1,2,0,2,8,0,0,0,1,1,0,1,0,1,1,5,4,4,1,4,1,3,1,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,3,2,0,2,6,1,5,3,0,3,2,2,0,7,3,4,3,1,2,6.76,9.33,5.73,17,4,13,10,6,4,14,4,10,3,0,3,5,26,0,4,0,0,18,4,0,0,9,13,5,31,0,0,0,9,1,8,32,2,30,26,9,26,9,9,9,15,2,32,3.56,0.8,7,2,3,6,0,0,9,8,1,9,1,0,9,3,8,0,8,1,7,0,8,2,1,5,3,3,7,3,2,5,8,2,0,7,2,6,1,1,1,2,7,1,*